fuzzball-muck/fuzzball

- .gitignore
- fbmuck/win32/version.cpp
Fix for the recent change made to the credits functionality on win32 machines. The prebuilt version.cpp for win32 still had the old do_credits definition in it. This caused the linker to complain about multiple definitions. This fixes it by deleting the do_credits function from the file.
Also updated the gitignore to ignore my compilation directories. Makes life a little easier for to not have to ignore all of that every commit.
> Win32 fix for credits change

- fbmuck/Makefile.in
- fbmuck/src/Makefile.in
The config.status script is a better way to recreate configure-generated files since it will pass the same configure flags as were passed to configure to generate it.
> Use ./config.status instead of ./configure to regenerate Makefiles

- fbmuck/include/defaults.h
- fbmuck/include/tune.h
- fbmuck/src/interface.c
- fbmuck/src/tune.c
TLS configuration recommendations (like [this](https://wiki.mozilla.org/Security/Server_Side_TLS)) typically advise using server cipher preference order over client (which is default in OpenSSL). This adds a tune to configure this OpenSSL option.
Also add a note to some SSL tune descriptions that they don't take effect until restart.
> Add option to honor server cipher preference order

- fbmuck/src/mfuns.c
There are several places in MPI where we permit a user to provide
a custom time offset overriding the timezone. To do this, we
mutilate UTC time before passing it to the `MUCKTIME()` macro.
However, we were doubling the value of `get_tz_offset()` in
these cases rather than negating it.
A cleaner solution to this would be using gmtime(), but we don't
know if that's available for our present compatibility goals.
Some historical tickets:
http://sourceforge.net/p/fbmuck/bugs/257/
http://sourceforge.net/p/fbmuck/bugs/271/
Testing done:
Create a MUCK with non-UTC localtime and test mpi codes before and
after the change:
{ftime:%m-%d %X,2}
{date:0}
{ftime:%Y-%m-%d %X,0,0}  # Should be epoch.
etc.
> Correct mpi time functions offset handling.

- fbmuck/include/config.h
- fbmuck/include/db.h
- fbmuck/include/externs.h
- fbmuck/makefile.win
- fbmuck/src/events.c
- fbmuck/src/interface.c
- fbmuck/src/mfuns.c
- fbmuck/src/mkversion.c
- fbmuck/src/mufevent.c
- fbmuck/src/time.c
- fbmuck/src/timequeue.c
- fbmuck/src/wiz.c
- fbmuck/win32/win32.h
Here's an explanation of the changes:
* Changed config.h to move the WIN32 stuff to the bottom. There were includes for header files after the win32.h include. So it would redefine some of the POSIX functions which would generate compile issues. This might have just been Visual Studio 2015 being a pain, but since that's released now I moved to it.
* Updated the windows makefile to include the timestamp file that was added, as well as updating the debugging options. Which I needed for some of these other changes.
* Changed the mkversion to include win32.h as the defaults no longer include the needed windows header files. 
* Changed win32.h to check of certain functions are defined before trying to define them. This avoids issues with popen and _popen for example.
* Changed some %ld's to …
> Win32 compile fixes

- fbmuck/src/version.tpl
A simple fix to disable GIT hashes from the "all" option if they weren't available at compile time.
> Fixed '@hashes all' so it doesn't show git hash if not available.

- fbmuck/fuzzball.cnf
Updated the fuzzball.cnf file with some better defaults. 4096 bits and sha256 over sha1. These will provide more security for people making their first certs.
> Updated fuzzball.cnf with more secure defaults

- src/interface.c
Apparently, by default, OpenSSL uses a single key for ECDH across all sessions in a server rather than generating a new key for each connection. This gives weaker forward secrecy properties than one would expect and thus is often disabled (e.g. both Apache mod_ssl and Nginx disable this feature). This patch does the same.
Also, disable session resumption, which isn't very useful for us (since clients don't rapidly reconnect to MUCKs):
- disable ticket support, which would break forward secrecy unless we were to regularly rotate the keys used to encrypt session tickets. 
- disable session cache support, where session IDs expire by default after 5 minutes (from connection start, it seems), but OpenSSL only clears expired sessions every 256 connections.
> Use SSL_OP_SINGLE_ECDH_USE; disable SSL session resumption

- include/config.h
- include/interface.h
- src/interface.c
Fixes problem where struct descriptor_data in interface.h will
be wrong when included from any file that doesn't set USE_SSL first.
> Move USE_SSL #define to config.h.

- game/data/help.txt
- include/config.h
- include/interface.h
- src/game.c
- src/interface.c
This pull request includes #12.
Add a Wizard-only command `@reconfiguressl` to reinitialize the SSL_CTX, including reloading certificate files. The new configuration will be effective for all subsequent connections. Notably, this allows certificates to be renewed without restarting a MUCK. It also allows changes to SSL @tunes to be effective without restarting.
In the event that reconfiguring SSL fails, for example because a new certificate file is bad, the old configuration remains active, and a vague error is given to the Wizard running the command and a less vague error appears in the log file.
> Add command to reload SSL configuration

- .travis.yml
Continuous integration allows for automated testing of commits and pull-requests, making it easier to verify if a set of changes breaks the build on some obscure configuration, while also a reliable way to build Fuzzball (*no confusion over "it works on my machine"*).
This pull-request enables the [Travis CI service](https://travis-ci.org/ ) for Linux-based building.  [Appveyor](http://www.appveyor.com/ ) or a similar service for Windows-based building will be addressed separately.
* Using the Travis continuous integration service, build with/without SSL and with/without IPv6 support using both GCC and Clang, resulting in a total of 8 different types of builds
* For example, see https://travis-ci.org/digitalcircuit/fuzzball
* Unfortunately, Travis does not yet have a way to [build a 2x2 …
> Enable Travis continuous integration

- src/helptk/edithelp.tcl
Specify ```-col``` as ```-column``` to resolve an ambiguous option warning in Tk version 8.6 (specifically, ```8.6.0+6ubuntu3```).  Otherwise, the Edit button displays a warning instead of displaying a useful editing window.
This might potentially cause issues on older versions of Tk, however, anyone upgrading to the [latest version 8.6.x](http://tcl.tk/software/tcltk/download.html ) will encounter this, including [Ubuntu 14.04's version](http://packages.ubuntu.com/trusty/tk ).
> edithelp: resolve ambiguous option '-col' to '-column'

- appveyor.yml
- conanfile.txt
- makefile.win
*Github [does not allow reopening a pull request](https://github.com/isaacs/github/issues/361 ) if the branch was force-pushed while the pull request was closed.  Pardon the noise, and now I know for next time.  This replaces pull request #22.*
Continuous integration allows for automated testing of commits and pull-requests, making it easier to verify if a set of changes breaks the build on some obscure configuration, while also a reliable way to build Fuzzball (*no confusion over "it works on my machine"*).
This pull-request enables the [Appveyor CI service](http://www.appveyor.com/ ) for Windows-based building, complementing the existing [Travis](https://travis-ci.org/ ) implementation.
* Using the Appveyor continuous integration service, build with NMake from Visual Studio 2015 …
> Enable Appveyor Windows continuous integration

- game/data/help.txt
- game/data/info/muckhelp
- game/data/muckhelp.raw
Update ```help.txt```, ```muckhelp```, and ```muckhelp.raw``` with documentation on ```@tune save``` and ```@tune load```.
As ```data/parmfile.cfg``` is defined at compile-time, it should be safe to reference it in the help.  If changed locally, one should modify the help, too.
> Add help for @tune save, @tune load

- README.md
- README_LINUX.md
- README_WINDOWS.md
* Move Linux build information to ```README_LINUX.md```, removing clutter from the main README
* Add draft of Windows build information to ```README_WINDOWS.md```, documenting setting up a build environment
* This information may be incomplete, feel free to change as needed.
* Update ```README.md``` to reference the stable downloads, additional help, and link to the new build pages as needed
* Add Appveyor build status to the top, right by the Travis tag
*For an example, see https://github.com/digitalcircuit/fuzzball/tree/ft-readme-windows*
> Reorganize README, add Windows information

- .gitignore
- Makefile.in
- game/data/help.txt
- game/data/info/muckhelp
- game/data/info/mufman1
- game/data/man.txt
- game/data/muckhelp.raw
- game/data/mufman.raw
* Add new tunable parameter ```consistent_lock_source``` to ```mufman.raw``` and related generated help files (```mufman1```, ```man.txt```).
* In the future, this portion of the help should be automatically generated, but for now keep it in sync so one can learn about it without reading the source or having a running server
* Re-add ```make help``` functionality using a new ```HTML_DOCS_DIR``` variable, currently set to ```docs_html```
* This makes the generated help functionality more obvious to new contributors and hopefully reduces confusion
* In the future, this should be cleaned up so all generated docs are made as part of ```make all```, and ```help.txt```/```man.txt``` should be removed from the repository (*don't forget to update ```Makefile.win```, too*)
* Update generated docs, …
> Fix help generation, formatting, add new tunable parameter

- README_LINUX.md
* Add the ```libpcre3-dev``` package to the Ubuntu ```apt-get install``` instructions.
* Make the PCRE library a link to the website
* Saves a quick Internet search for those who don't know of it.
> Update Linux README with PCRE package, website link

- dbs/advancedb/data/advancedb.db
- dbs/basedb/data/basedb.db
- dbs/fb-base/data/fb-base.db
- dbs/minimal/data/minimal.db
- dbs/regressions/data/regressions.db
- game/data/info/mufman1
- game/data/man.txt
- game/data/minimal.db
- game/data/mufman.raw
Follow-up to [removing ```sync_legacy_prop```](https://github.com/fuzzball-muck/fuzzball/commit/1896990c5e27e90bb2c505abded3777039bb6767 ).
* Remove from ```mufman.raw``` and generated help files
* Remove from starter and test databases
* No harm caused as unknown properties are ignored, but makes things a little more clean
*Pardon if you intended to get to this; no ill will meant*
> Tidy up sync_legacy_prop references

- game/data/info/mufman1
- game/data/man.txt
- game/data/mufman.raw
* Add new system parameters to ```muffman.raw``` and generated help files
* Helps avoid need to poke source code or a running server for reference
* In the future, this section could possibly be generated during compile
*Follow-up to [commit that added new 'Files' sysparms](https://github.com/fuzzball-muck/fuzzball/commit/90b9b9e6174659d10e1e7ca50f18dbf283bb1b78 ).*
> Update MUF manual with new file/folder sysparms

- appveyor.yml
- conanfile.txt
- makefile.win
* Clean up build system, using ```/build``` for binaries
* Modify ```conanfile.txt``` to put OpenSSL in this folder
* Allow modifying ```OUTDIR``` from ```makefile.win```, set this to ```/build``` in AppVeyor
* Modify ```makefile.win``` to optionally search for other packages
* Simplifies OpenSSL if in the future other packages are bundled, e.g. PCRE
* Minor cleanups after switching to pip-based Conan install
Impact | ★☆☆ *1/3* | Fixes automated builds, essential to see if other things break
Risk | ★★☆ *2/3* | Might break build setups that differ from AppVeyor, though it shouldn't
Intrusiveness | ★☆☆ *1/3* | Build system changes, shouldn't interfere with other pull requests
Separating build system output and input helps with …
> Clean up AppVeyor builds, part 1

- configure
- configure.ac
- include/autoconf.h.in
- include/fbsignal.h
- src/fbsignal.c
- src/interface.c
Our handlers for signals do async-signal-unsafe things, which might be the root cause of MUCK freezes on futex() calls reported in issue #40. One solution to this is to ensure the signal handler only runs at a safe time, such as when we would call select(), rather than processing it immediately. This patch tries to implement that solution for SIGUSR1 and SIGCHLD on systems that support pselect().
SIGUSR1 and SIGCHLD are masked out of the process except during a call to pselect() (which replaces calls to select()), so the signal handler should only run during the call to select(). I only do this for SIGUSR1 and SIGCHLD because these are signals we expect the MUCK to continue running after; for signals like SIGSEGV or SIGTERM it seems more important to attempt to do something right away.
> Use pselect() for SIGCHLD, SIGUSR1

- src/interface.c
- src/resolver.c
This fixes two problems with the external resolver code:
- addrout() in interface.c did not terminate resolver commands with a \n, so IPv4 resolutions generally wouldn't happen;
- the resolver code depended on fclose()ing stdin resulting fgets() returning an error, but I do not believe this happens consistently. This code checks the return value of fgets() under a lock to hopefully ensure that, when the resolver should shutdown, no other thread attempts to call fgets(). It also manipulated the shared variable shutdown_was_requested without a lock, which is illegal even though it is declared volatile.
This may fix a cause of issue #42.
> Send newline-terminated resolver commands, cleanup resolver process QUIT procedure

- src/array.c
avl == NULL appears to be how empty dictionaries are supposed to be represented, and array_tree_find behaves correctly for them (returning NULL).
May fix issue #44.
> Remove assertion that avl != NULL in array_tree_find

- include/interface.h
- src/interface.c
When a non-blocking SSL_write fails, OpenSSL requres the next write call to use the exact same buffer. We violate this requirement in some circumstances; in particular for QUIT and idle-boot messages and when output buffers fill up. This patch attempts to track whether an SSL_write failed with WANT_READ or WANT_WRITE and not discard the top element of the output queue in that case. This also modifies the idle-boot and leave message to use the output queue rather than calling socket_write() directly.
I created this while trying to diagnose issue #48, but I don't think it's likely to be that problem. (See also my 'tests' branch, in which I have some python scripts that start a MUCK and try to list a lot of MUF code, which is how I discovered this issue.)
> No repeat write

- include/db.h
- src/boolexp.c
- src/compile.c
- src/create.c
- src/db.c
- src/edit.c
- src/fbsignal.c
- src/game.c
- src/interface.c
- src/log.c
- src/look.c
- src/mcppkgs.c
- src/p_db.c
- src/property.c
- src/sanity.c
- src/set.c
- src/tune.c
- src/wiz.c
This patch fixes several memory leaks:
- my last patch didn't free the new priority_output or pending_ssl_write queue if a connection was dropped with pending output;
- unparse_object() calls strdup() sometimes, but none of the code using it free()'d the result (and sometimes unparse_object() returned a pointer to a constant, so they couldn't)
- whowhere() was called without free()ing the result
- SSL_free() wasn't called on closed ssl_session objects.
> Fix several memory leaks

- src/interface.c
Fixes some SSL-related memory leaks during shutdown/restart.
> Additional memory leak fixes

- src/interface.c
Sometimes we do zero-length writes, for which 0 is an expected non-error return value. Currently we treat that as an error.
> write() <= 0 ---> write() < 0 for error detection

- src/interface.c
And also make write_text_block return value be consistent when *qp is null
> Correct/add comments for write_text_block/write_queue return values.

- include/config.h
- include/interface_ssl.h
- src/interface.c
- src/interface_ssl.c
* Unify SSL logging
* Change `ssl_log_error()` into `ssl_check_error()`, replace `SSL_get_error` calls elsewhere
* Add `DEBUG_SSL_LOG_ALL` `#define` to `config.h` to control level of SSL logging
* Remove now-unneeded `log_ssl_error()` function from `interface.c`
* Unify `socket_read`/`socket_write`
* Move `#defines` into `socket_read()`/`socket_write()` functions
* Use `#ifdef`'s for SSL logic
* Fixes `last_pinged_at` not getting set to `null` when compiled without SSL
* Clean up comments, indentation
* Migrate `interface_ssl.(c|h)` to tabs for indenting, spacing for alignment
* Use `//` for comments, `///` for variabl and functions headers, [Doxygen style](http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html )
* Update OpenSSL links to fix 404 errors …
> Clean up SSL logging, optionally log all errors

- src/fbsignal.c
When multiple child processes die, we can sometimes receive two SIGCHLDs which only result in one call to our SIGCHLD handler running. This is considerably more likely with the pselect() patch ensuring that SIGCHLD handler is only run during pselect(). This patch modifies the signal handler to call waitpid() in a loop. It also moves the respawning of the resolver after the loop so that if it crashes immediately, that does not keep the child reaping loop from finishing.
> potentially reap multiple processes per SIGCHLD handler call

- src/interface.c
On further investigation of why I was observing two processes needing to be reaped in one SIGCHLD call I discovered that we spawned the resolver before any SIGCHLD handler was setup. Thus, if it crashes immediately, we lost the SIGCHLD, and reaped it the next time a dumper process crashed.
This patch moves starting the resolver until after set_signals() is run.
> spawn resolver after signals get setup

- src/interface.c
This should work, with both SSL and USE_IPV6.
@wyld-sw's patch tried to rely on preprocessor symbol IPV6, which is not the appropriate one.  As well, it tried to rely on the count of ipv4 sockets in both plaintext and ssl versions to figure out how many ipv6 sockets to listen on.  This corrects both shortcomings.
Feel free to change line and white spacing.
> Fixing @wyld-sw's fix to start listening on IPv6 sockets

- src/interface.c
Recent rearranging of when socket binding happens seem to have moved configuring SSL settings to before the database or parmfile is read with, for example, the location of the certificate file to use. This patch seperates out binding the SSL sockets from configuring the SSL settings.
> configure SSL after reading settings from parmfile/DB

- appveyor.yml
* For version, use tag if available or short commit hash if not
* Simplifies associating downloads and builds to a particular commit or tag
* Update the artifact name to include the build version
* Allows distinguishing downloads
Impact | ★☆☆ *1/3* | Dev. quality-of-life improvement, easier tracking of bad builds
Risk | ★☆☆ *1/3* | Easily reverted, only changes build packaging
Intrusiveness | ★☆☆ *1/3* | Minor changes, shouldn't interfere with other pull requests
* AppVeyor interface
* URL: https://ci.appveyor.com/project/digitalcircuit/fuzzball/build/207
* Downloads
* File: `fuzzball-win32.zip`
* Folder inside: `fuzzball-win32-207/`
*Tagged builds are now handled differently from regular commits.  Tag is `7.00a1-test`*
* AppVeyor …
> More descriptive AppVeyor build numbers

- include/fbsignal.h
- src/fbsignal.c
It turns out that waitpid() returns 0 if called with WNOHANG and
there are no errors.  The prior commit only checked for -1, which
is returned only on an error.
This commit removes a spurious if(), and makes errno available
to be logged if waitpid() actually returns -1.
>     Fix looping issues with new waitpid() loop in sig_reap()

- src/msgparse.c
An off-by-one error in msgparse.c breaks access to MPI functions whose names are exactly MAX_MFUN_NAME_LEN characters in length (default 16), and shorthand {&var} access to variables whose names are one less (15).
> Fix off-by-one in MPI variable/function parsing

- .travis.yml
- game/data/help.txt
- game/data/info/muckhelp
- game/data/muckhelp.raw
- src/Makefile.in
* Fix `prochelp` build
* Add an explicit makefile rule for `prochelp` so includes apply
* Fixes `db.h` not found errors [after token replacement was added](https://github.com/fuzzball-muck/fuzzball/commit/3b32f2d8315e14c98df9efef76210e2faeb67f15 )
* Add `prochelp` to `make all`, ensuring CI tests it can build
* Remove `prochelp` as part of `make clean`
* Rename `@dbginfo` to `@debug`
* Include example usage
* Adds on to [commit 6ae4c9a](https://github.com/fuzzball-muck/fuzzball/commit/6ae4c9a820967e42147b4763340f37cbf4d7045d )
Impact | ★★☆ *2/3* | Fixes help generation, improves tests, updates docs
Risk | ★★☆ *2/3* | Might break generating help on other non-standard build setups
Intrusiveness | ★★☆ *2/3* | Modifies build and help …
> Fix prochelp build, add to CI, rename @dbginfo docs

- src/create.c
- src/look.c
In copy_one_prop, we call alloc_string() before calling set_property, but set_property calls alloc_string again (in set_property_nofetch), so this leaks memory.
In listprops_wildcard, we make copies of global strings (representing gender/etc. property names) rather than just reading the original. We also make a heap copy of the stack copy of current property name for no reason I can ascertain.
> Fix some small property handling memory leaks

- src/property.c
I missed a few copies of code that needlessly strdup()'d tp_gender_prop and LEGACY_GENDER_PROP. .
> Fix gender_prop-related memory leaks

- src/boolexp.c
When we load lock properties, we currently check that any absolute DBRef in the lock is a non-garbage object. Since we haven't loaded objects yet, this check can access uninitialized memory and may erroneously detect garbage. This patch removes the check.
> Avoid referencing unloaded objects when loading lock props

- src/p_regex.c
REGSPLIT leaks memory, primary by allocating strings, passing them to array_appenditem(), which copies them, but not deallocating the original. This patch fixes those leaks. It also fixes a leak of the result array in case of a weird PCRE errors.
> Fix memory leak in regsplit.

- src/p_error.c
When normalizing error type strings to compare to the table of possible types, functions in p_error make a non-null-terminated uppercased copy of the string, which will sometimes break the comparison. This patch makes sure that copy is null-terminated.
> Null-terminate uppercased strings in p_error.c

- src/p_strings.c
STOD tries to return #-1 (nothing) for non-numbers, but it doesn't correctly identify most non-number strings.
> Make STOD return #-1 from non-numbers

- src/p_strings.c
prim_subst checks whether j + 1 > BUFFER_LEN before writing to index j + 1, allowing it to write one past the end of the buffer.
> fix off-by-one error in prim_subst

- src/inst.c
When insttotext tries to output a dictionary keyed by strings but does not have enough space to show all the keys, it can leak memory for memory for the first key-value pair it did not completely show because it relied on array_next() cleaning up the struct inst.
> fix memory leak in insttotext

- src/p_array.c
- src/p_misc.c
- src/p_stack.c
- src/p_strings.c
Fix various places where stack underflow/overflow is not properly checked and where operands may be CLEAR'd the wrong number of times if abort_interp() happens.
> Fix various stack overflow/underflow/premature CLEAR problems.

- src/game.c
This keeps the resolver process from sticking around as a zombie on panic(). We could instead attempt an orderly shutdown of the resolver, but I'm not sure how we'd handle failures during this.
> SIGKILL resolver on panic().

- include/interp.h
- src/interp.c
- src/p_array.c
- src/p_stack.c
Before and after each primitive, check that we've used one of the macros in interp.h to verify that we  could pop and push the stack as much as we did. This also splits up those macros to provide options for some stack manipulation primitives that do something strange and to provide versions that don't set `nargs`, which needs to be synchronized with how many of the oper{1,2,3,4} variables are in use.
> Add debugging-only code to check stack underflow/overflow checking.

- src/compile.c
Also removes call() check for PUBLIC/WIZCALL declarations that is redundant with the subsequent search for the procedure starting word.
> Fix various memory leaks in MUF compilation error handling.

- src/interp.c
This adjusts a previous patch that verified that the amount pushed matched CHECKOFLOW usage to not trigger when an error is signaled instead.
> Be less picky about push checking when primitives error out

- src/p_array.c
I assume there's some reason why this was written this way in the first place, but I can't figure it out.
> Remove apparently redundant code from ARRAY_NINTERSECT

- src/p_db.c
The MUF primitive GETLINKS didn't check for stack overflow.
> missing overflow checks in GETLINKS

- include/props.h
- src/p_db.c
- src/property.c
create_player overwrites player fields. This includes overwriting some default properties, like `@/value`, which causes memory to be leaked if the 'properties' field of the `struct object` is replaced. This patch instead sets up a function to copy the properties over the existing properties. It also includes setting `next`, which corrupts the location list of player_start.
> Don't overwrite initialized properties/fields in COPYPLAYER

- src/p_stack.c
To cooperate better with push/pop sanity checking code.
> use EXPECT_WRITE_STACK instead of CHECKOP in prim_rotate

- src/property.c
next_prop_name(), which is used by the MUF primitive NEXTPROP, will give a property name not prefixed with / when given an empty string as starting property name, even though it returns a /-prefixed property name in all other cases. This means that `#1234 "" NEXTPROP` will give a property name that does not start with / except when a non-readable property/propdir was skipped over. This patch special-cases the empty string to add a slash to the returned property.
Since this changes user-visible behavior of NEXTPROP, this change may have compatibility issues.
> make first prop from next_prop_name always start with /

- src/p_math.c
Some MUF like `"this is a long string" 200000000 *` can trigger an integer overflow in the length check for the resulting string, possibly resulting in a buffer overflow. This patch tests explicitly checks for this problem.
> Check for integer overflow in prim_multiply with strings.

- src/p_math.c
Special case string multiply by 0 or multiplying zero-sized string by anything instead of dividing by zero or dereferencing a null pointer or entering a potentially large number of for loop iterations.
> Handle string multiplies by zero correctly.

- src/compile.c
- src/p_math.c
Dividing MININT by -1 (including in taking the modulus) overflows, and on many systems, this overflow results in a fatal signal. This patch detect this situation instead in the implementation of prim_divide and prim_mod and constant folding for them.
> avoid MININT/-1 and MININT%-1 in MUF implementation

- src/mfuns.c
Currently {func:foo,x,y,z,...} does not actually define the variables x and y within the function. This patch fixes that problem.
> Handle multi-argument MPI functions with {func:...}

- src/compile.c
This fixes a use-after-free when trying to compile the following MUF program:
```
$
```
> Set next_char to NULL when line_copy is set to NULL.

- src/compile.c
This patch prevents compiling a (bizarre) MUF program like `: x ; if then` from causing an out-of-bounds write.
> Don't set flags on out-of-bounds instructions in OptimizeInermediate

- src/compile.c
Like `: main[` or something with too many arguments.
> fix memory leak when compiling ": main[" (premature end-of-file)

- src/compile.c
Addresses #115.
Right now we mostly compile code that should be unreachable outside procedures, but not completely. For example, we try to do peephole optimization on this code, but may not correctly resolve loop and branch references in this code or handle any loop nesting issues in it. This patch simply makes these cases a compile-time error. This fixes a some memory errors/other weird behavior, for example from:
`begin : main repeat ;`
or
` : main 1 ; for`
This patch may break some MUF programs that have benign code outside procedures.
>  Refuse to compile MUF code that does things outside procedures 

- src/compile.c
This fixes a memory leak when trying to compile something like `: $ifver   + ;`
> MUF: Don't try to parse more tokens after directive fails to parse.

- src/mfuns2.c
Also correct argument numbers in error messages.
> Check validity of who argument in MPI testlock before using Typeof() on it.

- src/fbtime.c
At least glibc's localtime() can return a NULL struct tm when given a very large time_t (e.g. 100000000000000000), which otherwise triggers a NULL pointer dereference something like the MPI
"{ftime:%a,,100000000000000000}".
> Don't crash when the struct tm* passed to format_time is null.

- src/p_stack.c
Since this is such a simple and easy thing to fix, I figured I'd just do it rather than open an issue pointing the problem out.
This changes `CHECKARGS` to correctly report what it expects when it encounters HOME (#-3) at argument specifiers "t", "e", or "f".
> Typo patrol: Correctly report what CHECKARGS expects.

- src/move.c
This fixes an out-of-bounds heap access from running:
```
@create Zombie
@force Zombie=get #0
```
> do_get: don't try to find Typeof(NOTHING) if someone does 'get #0'.

- src/p_float.c
Setting nargs = 6 keeps do_abort_interp() from clearing any of the oper1/2/3/4 variables, which can leak memory.
> diff3: CLEAR() correct number of items on abort_interp().

- src/mfuns.c
- src/p_misc.c
Passing a huge time_t to localtime() can make it return NULL. This patch makes doing this from MUF or MPI result in an error instead of crashing the MUCK.
> Handle MUCK_LOCALTIME() failing on huge time_ts.

- src/props.c
copy_proplist() can overwrite property values without freeing old values. This can be triggered by calling COPYPLAYER, where the pname history property will be generated, then may be immediately overwritten by the copy, causing a memory leak of the original string.
> clear old propnode values in copy_proplist

- configure
- configure.ac
- include/autoconf.h.in
- src/edit.c
- src/game.c
- src/interface.c
- src/interp.c
- src/mcp.c
- src/mcpgui.c
- src/timequeue.c
- src/tune.c
When running leak detection tools like AddressSanitizer, its useful if the MUCK frees memory on exit. Currently this is done when malloc profiling is turned on, but not otherwise. This patch should make this a separate option which is also enabled by enabling malloc profiling.
> Add compile option for free'ing memory on exit

- src/tune.c
This addresses one of the problems found in #126.
> fix memory leak in do_tune when old value is ""

- src/boolexp.c
This seems to fix one of the bugs mentioned in #126.
> check bounds when stripping trailing spaces in parse_boolexp_F

- src/compile.c
This seems to fix the memory leak on compiling ': main FOR IF BREAK' mentioned in #126.
> free auxillary CONTROL_STACK data on compile error

- src/fbstrings.c
This should fix an out-of-bounds read mentioned in #126.
> don't let [abc] SMATCH end of string

- src/msgparse.c
This should fix some memory leaks in mentioned in #126.
> free MPI arguments when premature end of string encountered

- src/msgparse.c
Avoid leaking memory when reporting some MPI errors.
One of these is a leak involving {while:...} mentioned in #126.
> free MPI values before aborting for some errors

- src/p_stack.c
CHECKOP() sets nargs(), so abort_interp() will try to erroneously CLEAR
the appropriate number of oper* variables.
This fixes the assertion failure from `: main pop "" 0 over main and and ;` mentioned in #126. (The program makes the OVER primitive overflow the stack, which causes CHECKOFLOW() to trigger an abort that tries to clear oper1, which is null.)
> Do not use CHECKOP() when oper* variables aren't being used.

- src/p_stack.c
This prevents something '10000 POPN' from double-CLEAR'ing oper1.
> avoid clearing oper1 when we might call abort_interp without reseting nargs

- src/interp.c
There are some times when we check argument-by-argument for correct types after checking for the number of arguments, for example, in array_n_diff.
> do not assert pop depth if err is set

- include/interp.h
EXPECT_POP/READ_STACK can call abort_interp() which uses nargs.
> reset nargs during CHECKOP stack depth check to avoid re-CLEAR() oper[1234]

- src/p_stack.c
Previously, this code copied the size into an int, which might be smaller
than oper1->data.number, and overflow in the n < 0 case.
> prim_rotate: avoid overflow in comparing size

- include/db.h
- src/compile.c
- src/db.c
- src/interp.c
This should address #156.
This patch adds to the program_specific struct to track when we are currently running a primitive for a program. This avoids breaking any programs that might rely on editing or uncompiling other programs in this way, though I'm not sure that's actually a concern.
> avoid compiling program from within program primitive (e.g. FORCE)

- include/defaults.h
- include/tune.h
- include/tunelist.h
- src/interp.c
This limits the total number of interp calls before returning control
to the event queue (not just the nesting depth). This ensures that there is
a limit on how long MUF code can run before commands are read even
in the case of massive recursive program uninterruptible program
executions.
This adds two `@tune`s, one for the setting for mucker level 4 programs, one otherwise.
When programs are not in preempt mode, hitting the limit causes them to enqueue themselves on the timequeue. Otherwise, they are aborted.
This addresses #162, though perhaps default limits should be lower.
> Add setting to limit total number of interp_loop calls in any interp_loop

- src/debugger.c
(This can happen, for example, due to hitting the PREEMPT instruction
limit.)
> Give correct backtrace when aborting on the INIT FUNC instruction.

- src/interp.c
- src/p_math.c
This is a change that may break backwards-compatibility. (But note that the calculations were always done with int precision, regardless of type.) This addresses #127.
For BITSHIFT, to avoid undefined behavior this patch modifies the implementation to:
- perform left shifts with unsigned integers;
- never perform shifts by an amount more than the width of an int
> make bit* primitives check for INTEGER type; avoid undefined behavior in BITSHIFT

- include/interp.h
The program?/etc. primitives can pass #-3 to CHECKREMOTE.
> CHECKREMOTE: tolerate HOME (#-3).

- src/array.c
This avoids a crash from something like 
`{ "foo" "bar" }dict 1 { "foo" "bar" }dict array_pin tuck ARRAY_INSERTRANGE`
(when --enable-debug is on)
> array_insert/setrange: do not iterate over array while modifying it

- README_LINUX.md
- game/data/help.txt
- src/set.c
This PR introduces three changes:
1. Players of at least M2 may now set programs ```BOUND```;
2. The use of ```BOUND``` on rooms is now mentioned in user-visible documentation; and,
3. Even though the ```int restricted(dbref player, dbref thing, object_flag_type flag)``` function in set.c isn't called for M1, M2, or M3, their cases in that function now return appropriate values.
> Nonwiz bound and bound rooms

- src/fbstrings.c
This avoids going out of bounds in the following strcpyn().
> strdecrypt: check for and reject <2 character strings.

- src/mfuns2.c
- src/p_misc.c
This allows recycle() to avoid recycling a thing currently running a program that is force'ing the recycle to happen.
This also changes what FORCEDBY_ARRAY returns.
> push forceing players/zombies on forcelist

- appveyor.yml
* Use branch/commit info only for packaging; don't change AppVeyor build numbers
* Builds from before this commit won't be changed
* Fixes Github's `Details` link for in-progress builds giving a `404`
* Partially reverts 233f40c76f1b38e8556f407379703dbff330aea8
Impact | ★☆☆ *1/3* | Fixes Github links for unfinished builds, dev. quality of life
Risk | ★☆☆ *1/3* | Changes build URLs for future AppVeyor builds, easily revertable
Intrusiveness | ★☆☆ *1/3* | Build system changes, shouldn't interfere with other pull requests
Unfortunately, Github only updates the build link when AppVeyor finishes building.  If one tries viewing a build before it's done, the `Details` link returns a `404` as it points to the old build version.  Having …
> ci: Use AppVeyor's default build numbers

- src/timequeue.c
This keeps us from free'ing a program frame from prim_timer_start(). This doesn't remove enforcement of process_timer_limit `@tune`.
> Don't enforce max_process_limit or max_plyr_processes upon creation of timer events

- README.md
- README_LINUX.md
- README_WINDOWS.md
* Update README Markdown formatting to be consistent
Impact | ★☆☆ *1/3* | Fixes appearance of developer docs, first impressions
Risk | ★☆☆ *1/3* | No functional changes, trivial to revert
Intrusiveness | ★☆☆ *1/3* | Only touches README, shouldn't interfere with other pull requests
A while back Github changed required indentation for their Github-flavored Markdown, among other steps to unify with CommonMark.  This fixes the formatting to show as it should.
See: [Github Engineering blog: A formal spec for GitHub Flavored Markdown](https://githubengineering.com/a-formal-spec-for-github-markdown/ )
[README.md as of 73676ce5b29e5d638512c3a03884994e05b9d1c5](https://github.com/fuzzball-muck/fuzzball/blob/73676ce5b29e5d638512c3a03884994e0 …
> docs: Update README Markdown formatting

- game/data/man.txt
- game/data/mufman.raw
The stack-effect comments in the documentation for the MUF primitives `MD5HASH` and `SHA1HASH` were `( s -- )`, as though the hash string was being stored in a system variable or something. This PR corrects them to `( s -- s' )` in both mufman.raw and man.txt.
> Docfix: MUF primitives MD5HASH and SHA1HASH

- include/mcppkg.h
- src/mcp.c
- src/mcppkgs.c
The MCP org-fuzzball-languages package allows clients to query what extension languages the server supports.
The client sends the org-fuzzball-languages-request message with no args, and the server will send back an org-fuzzball-languages-supported message with a languages list argument, where each line is a language name and a version number separated by a colon.  Currently, the only response is "muf:7.0".
> Added MCP package org-fuzzball-languages.

- conanfile.txt
- makefile.win
* Switch to Conan's new, maintained [OpenSSL package](https://bintray.com/conan-community/conan/OpenSSL%3Aconan )
* Replaces the legacy OpenSSL package from before [the Bintray move](http://docs.conan.io/en/latest/packaging/using_bintray.html )
* This was planned in the past, but Conan's package didn't have 32-bit builds for a while
* Detect if OpenSSL packaging specifies a `MD` suffix
* Some OpenSSL packages specify it as `libeay32MD.lib`, `ssleay32MD.lib`
* Conan switched to specifying it as `libeay32.lib`, `ssleay32.lib`
Impact | ★☆☆ *1/3* | Fixes automated builds, important to see if other things break
Risk | ★☆☆ *1/3* | Potential incompatability with newer OpenSSL version, easily revertable
Intrusiveness | ★☆☆ *1/3* | Build …
> ci: Use Conan OpenSSL, use semantic versioning

- src/interface.c
`d->ssl_session` isn't set for non-SSL connections, so SSL_get_cipher_name() gets passed a NULL and chokes.
> Fix crash when non-SSL descriptor logs in

- appveyor.yml
* Specify the path to `conanfile.txt` when calling `conan install` on Windows
* Fixes the build failure due to invalid command line arguments
* Changes resulted from the [upgrade to Conan v1.0, as per the documentation](http://docs.conan.io/en/latest/conan1.0.html#command-line-changes )
Impact | ★☆☆ *1/3* | Fixes automated builds, important to see if other things break
Risk | ★☆☆ *1/3* | Potential incompatability with older Conan versions, easily revertable
Intrusiveness | ★☆☆ *1/3* | Build system changes, shouldn't interfere with other pull requests
```
ERROR: Exiting with code: 2
conan : usage: conan install [-h] [-g GENERATOR] [-if INSTALL_FOLDER] [-m [MANIFESTS]]
At line:2 char:1
+ conan install -s arch=x86
+ …
```
> ci: Fix Windows conan install flags for v1.0

- include/array.h
- include/interp.h
- src/array.c
- src/interp.c
- src/p_misc.c
This partially addresses issue #199.
This creates a linked list of all array allocations for each program. When the program is freed, all arrays on this list are cleared, to clean up circular references that weren't dealt with by reference counting.
To minimize modifications to existing code, a global variable indicates what list new arrays should go on. This is set by the MUF interpreter before and after running MUF primitives and reset on interpreter exit/abort.
To deal with cases where arrays are shared between MUF processes, FORK and EVENT_SEND are changed to do deep copies of any passed array.
I suspect I may have missed some cases where arrays can be passed between or into MUF programs.
> track array allocations with their responsible program to cleanup circular references

- game/data/mpihelp.raw
The word italic and the word overstrike were notably missing, the other words were re-organized to be in the same order they are defined in color.h
> Make mpihelp.raw information for attr correct

- game/data/mpihelp.txt
Also reorganize the attributes as before, to match the sensible order in color.h
> add italic+overstrike to mpihelp.txt

- src/mfuns2.c
add missing attributes, re-organize others to be the same order as in color.h and other documentation on ANSI colors
> Fix error message for mfuns2.c

- game/restart.in
The \ were unneeded and ended up in the error message itself.  The quotation marks were unneeded since variables expand within double quoted strings.
> fix a couple error messages

- LICENSE.md
GNU publishes their own markdown GPL3 here:
https://www.gnu.org/licenses/gpl.md
It has some differences in formatting.  Should the official gpl.md replace this current one? (of course with the openssl exception added back in)
> fix link + question

- dbs/advancedb/muf/85.m
I noticed, on Here Lie Monsters, that when a player has been connected for over 100 days, and their idle time is over 60 seconds but under 600 seconds (usually uncolored!) that the rainbow text applied to their 'on for' time can get applied to their idle time.  This diff makes it so that the idle time is always uncolored for that time period, regardless of other factors.
Diff partially tested.  I didn't leave a MUCK running for 100 days, nor enabled the rainbow text at an earlier time.  Diff works correctly though.
> Fix a rare color issue in advancedb WHO

- src/fbtime.c
`timestr_long` had a bug in it that would only print out the last value from the time array. You could see this by using `@mpi {ltimestr:61}`. This should have produced `1 minute, 1 second` but it instead produces `1 second`. This is because snprintf can't be used to print into the same buffer from which it's reading. As per the man page for snprintf:
> Some programs imprudently rely on code such as the following
> 
>     sprintf(buf, "%s some further text", buf);
> 
> to append text to buf. However, the standards explicitly note that the results are undefined if source and destination buffers overlap when calling sprintf(), snprintf(), vsprintf(), and vsnprintf(). Depending on the version of gcc(1) used, and the compiler options employed, calls such as the above will not produce the …
> Adjusted timestr_long to properly concatenate strings.

- src/prochelp.c
Compiler warnings showed me that in one of my previous diffs, I had entirely removed usage of the 'cols' argument from a couple functions.  Fixed that.  Likely a few more places cols will be removed in the future, too.
> Remove unnecessary function arguments

- game/restart.in
There are only a couple reasons why the logs directory wouldn't exist: a user not copying the game directory post-install as detailed in README_LINUX.md, or the log directory being moved or deleted at some later date.
https://github.com/fuzzball-muck/fuzzball/issues/235
Nonetheless, this diff fixes the above issue by creating the logs directory if it doesn't already exist.
> Let server start when logs directory doesn't exist

- game/data/mpihelp.raw
- game/data/mpihelp.txt
Both in .raw and .txt now.  (the HTML files aren't included in the repository or the release .tar.gz, are they included in the .zip?  I suspect not)
> Fix typos in MPI documentation, second attempt

- src/fbtime.c
This removes a BSD/GNU extension and instead uses a _XOPEN_SOURCE extension.
Please check this pull yourself before putting it anywhere, especially since I don't know the C preprocessor well.  the define/ifdef stuff.  I think it's right, though.  (And the C itself, I know is right)
But it turns out the solution was already there (albeit improperly there) in the code, hidden in the lower side of the ifdef.
I've confirmed this works on GNU/Linux GCC and OpenBSD Clang and GCC.
I can test it on FreeBSD Clang when I switch back from Ubuntu to FreeBSD, if you'd like me to test there too.
I thought the Windows builds build in Visual Studio now.  What's the fate of this cygwin stuff?  Is anyone still building it that way?  If we get rid of it, will Windows builds still work?
SunOS was …
> Make fbtime.c more portable

- game/data/man.txt
- game/data/mpihelp.html
- game/data/mpihelp.raw
- game/data/mpihelp.txt
- game/data/mufman.html
- game/data/mufman.raw
- src/fbtime.c
I'll leave the BSD (tm_gmtoff-based) polarity of the result rather than the SysV (POSIX, SUS) polarity of the result, for backward compatibility with existing fuzzball installs.
And document it, too!
> Remove a cygwin ifdef, update docs

- game/restart.in
ulimit here was likely useless, and DEFINITELY nonportable
> Remove ulimit from script

- .travis.yml
I've seen some bugs more obviously show up during make install.  I remember in some of my builds, seeing prochelp segmentation fault during make install (which includes make help) let me know something was wrong with a diff I wrote.
Including the very quick make install lets such a chance be possible, to see prochelp segfault or run OK.
Also, switch to the newest version of Ubuntu that Travis has available.
btw is there a difference between make and make all for fuzzball?
> Update .travis.yml attempt 2

- src/fbtime.c
Now get_tz_offset() uses only standard C, not even POSIX or X/Open extensions...  In return, I have to do the calculations myself, which is fine.
> Make fbtime.c super portable

- game/data/man.txt
- game/data/mpihelp.html
- game/data/mpihelp.raw
- game/data/mpihelp.txt
- game/data/mufman.html
- game/data/mufman.raw
The list of conversion specifiers had many errors, in timefmt's documentation.  I documented that timefmt and ftime use strftime(), and replaced the list of conversion specifiers with one more similar to the one in the C standard. (the C17/C18 standard's list of specifiers is compatible with the C99 one, btw)
> Improve timefmt and ftime's docs

- src/interface.c
Spotted this in appveyor's output, after ipv6 was enabled for all builds.  Also checked the ipv4 version, and fixed it too.
While there, fixed some stylistic discrepancies between the two, and made a comment more readable.  I wonder if the situation described in the comment still exists as of this decade or not, but I won't touch that.
> Fix time_t to int conversion

- src/boolexp.c
- src/compile.c
- src/create.c
- src/db.c
- src/debugger.c
- src/interface.c
- src/mfuns.c
- src/mfuns2.c
- src/p_misc.c
- src/p_strings.c
- src/prochelp.c
- src/propdirs.c
- src/property.c
- src/props.c
- src/resolver.c
- src/set.c
- src/tune.c
Also rindex() with strrchr().  Each function is replaced with an entirely identical function, the only difference is the name.  Before, this was done using some #define in config.h.  Now, we're one step closer to getting rid of the string.h/strings.h mess in config.h.
(moving from BSD/strings.h functions to standard/string.h functions, in this case)
> Replace index() with strchr()

- .travis.yml
Attempt 2.  What did does is make Travis build the no-options and all-options builds first.
In the past, the no-option build was always last.  This provides more variety to the immediate results.
> Change matrix order

- include/config.h
I believe this is safe because we already include fcntl.h, sys/types.h, and unistd.h, and I've even seen on some systems (through googling) that sys/file.h is often blank and empty, other than including those things.
On systems where it has stuff, I don't think fuzzball uses anything from it.
future directions: remove the ifdef around stdlib.h and unistd.h, if possible.  (this should definitely be possible for stdlib.h, maybe not for unistd.h)
> Don't include sys/file.h

- include/config.h
It's never going to be something we don't have, on any working C compiler.
future directions: get rid of STDC_HEADERS and HAVE_STDLIB_H defines
> Always include stdlib.h

- include/db.h
- src/crt_malloc.c
- src/db.c
- src/fbmath.c
- src/fbstrings.c
- src/interface.c
- src/p_math.c
- src/p_strings.c
Replace legacy function names with standard C function names.
future directions:
finally get rid of the string.h strings.h memory.h ifdef stuff in config.h :D  and just include both string.h and strings.h
figure out which memmove() can safely be replaced by the more efficient memcpy()
> Replace bcopy and bzero with memmove and memset

- dbs/advancedb/data/advancedb.db
Changing the ftime format to just %c for the date and time, most importantly.
Switched from \[ to MPI attr, and at the same time, made the usage of bold text more consistent.
Also got rid of extra alignment spaces since this isn't a table of data.
> Update advancedb time/uptime

- src/look.c
I was checking the in-game uptime, and saw something.
%c defaults to %a %b %e %T %Y (though it may be different in foreign locales)
By swapping the position of the year and time zone abbreviation, we can simplify the format, and also future-proof fuzzball for internationalization.
> Change some strftime formats in look.c

- README_LINUX.md
- src/Makefile.in
Move restart command to sbin.  Renamed it so it won't conflict with other programs on a Unix system that might have restart scripts.  Move documentation files to share/doc/fbmuck rather than share/fbmuck
FUTURE DIRECTIONS:
move fbmuck and fb-resolver to sbin
have help files not originate from game/data/, but maybe from docs/
figure out why GNU autostuff uses "install -c" instead of "install", even for other uses...
> Better adhere to Unix hier

- src/p_props.c
This fixes ".\src\p_props.c(576): warning C4101: 'tmpe': unreferenced local variable" in https://ci.appveyor.com/project/fuzzball-muck/fuzzball/branch/master
Indeed, tmpe was not used in this function prim_setprop anymore.
Also, what are these spare curly braces (now at line 575 and 613) doing?  They introduce a new scope, for naming variables.  But I don't see variables with the same names (tname, propdat, len) being used elsewhere in prim_setprop outside of that scope.  And fuzzball compiles fine when the two brackets are removed.
Looking at github blame, they've been around since the original move to github from cvs.  (there are also similar cases of extra braces in this file, too)
Note I'm a big newb to C so I might be missing something.
OH WAIT, I SEE THE ANSWER: according to …
> Get rid of an unused variable tmpe in p_props.c

- dbs/advancedb/muf/59.m
- dbs/basedb/muf/16.m
- game/data/help.txt
- game/data/muckhelp.html
- game/data/muckhelp.raw
- src/speech.c
This wording for sending a location reduces potential confusion with the 'whereis' command available on many MUCKs, and clarifies what page is doing.
In this pull request is also some corrections to the documentation, which incorrectly documented the behavior of basedb/advancedb page instead of fuzzball's page, for sending messages.
> Improve page's wording for recipient

- include/config.h
errno.h is what the C standard and the POSIX standard use.  sys/errno.h isn't something I see mentioned anywhere.  (in fact, on FreeBSD they're identical files, and on OpenBSD, errno.h includes sys/errno.h and then adds more functionality)
resolver.c already specifically includes errno.h, so if this was going to break anything, resolver would already be broken.
TODO: get rid of the checks in autoconf for this
long-term TODO: fix this in fb5's final/bonus release since it causes fb5's build to fail on OpenBSD :P
> include errno.h

- .cirrus.yml
- .travis.yml
When building on a CI, remove -g and -O2 flags from src/Makefile after configure is run.
> Speed up CI builds

- configure.ac
- include/autoconf.h.in
- src/fbsignal.c
- src/resolver.c
Got rid of sys/signal.h since we include signal.h all the time. Got rid of RETSIGVAL since those functions are void, returning nothing.  Also replaced our_signal() with signal() since it's already defined to be signal() on non-POSIX systems (ergo it behaves the same, unless there's a bug) and POSIX systems do have signal().
No functional changes here!
TODO: make new configure script based on new configure.ac
Doing this to have the CI checks run without erroring out simply by being cancelled. :P
> signal-related cleanup attempt 2

- src/prochelp.c
bufsize is always a size_t, and pos is only ever compared with bufsize.  Up pos from int to size_t (which CI checks say is an unsigned long)
I still think strcpyn could be replaced with some usage of strncpy...  But this is just a small easy fix for this comparison warning for now.
> Fix size_t to int comparison in prochelp

- src/help.c
- src/tune.c
There's also double negation in property.c but it belongs there since it's saved into an int.
> Get rid of double negation where return value is already usable in boolean expression

- include/interface.h
- src/interface.c
This is similar to the X-Forwarded-For request header in HTTP.
The purpose is to provide administrators running a FORWARDED
aware proxy or webclient accurate hostnames in WHO*.
A client must indicate their desire to use this option with
IAC WILL FORWARDED and receive a IAC DO FORWARDED in response,
after which they may at any time send a sequence like:
IAB SB FORWARDED <hostname> IAC SE.
This is only supported for gateways running on the localhost.
> Ip forward

- game/data/info/mpi-intro
Document it in mpi-intro since that's where \r to CR is documented for users.
Also document, after testing, that backquote must ALWAYS be quoted in order to be displayed.
> Document \[ to ESC

- include/autoconf.h.in
- include/fbmath.h
- src/fbmath.c
I think that's all, for getting rid of standard C header ifdefs.
Potential TODO: get rid of posix header ifdefs?  unistd.h and dirent.h are what I'm thinking of.  From what I understand, fuzzball wouldn't work without them...  But I'm keeping that for a separate diff, since those'll have to go into a ifndef WIN32 zone.
Also should check each define in autoconf.h.in for whether we're still using them or not.  Some of them are definitely unused and might never be used again.
This diff includes stdint.h, gets rid of some mediocre typedefs related to that, and gets rid of a few things no longer used in autoconf.h.in
> Include standard C headers

- include/autoconf.h.in
- include/config.h
If we don't have unistd.h, we can't even build at all, on modern systems.  fork() and a lotta useful stuff exists there on posix.  So, simply require it.
TODO: check on dirent.h too.  But because it actually IS optional in Fuzzball because of DIR_AVAILABLE, I leave it for another commit.
> Always include unistd.h on Unix

- docs/help.txt
- docs/man.txt
- docs/mpihelp.txt
- docs/muckhelp.html
- src/muckhelp.raw
Have examples use say and pose rather than " and : shorthands.  Shorthands are still documented.
Also correct typos.
> Use normal commands as examples in help

- dbs/minimal/data/minimal.db
- game/data/minimal.db
Did this by wiping sysparms from db manually and saving what fuzzball itself saves back to db.
Does anyone know what the now-gone sysparm is?  I remember some have been recently removed.  (and the number is 157 instead of 158 now...)
I manually deleted all but one sysparm in minimaldb, changed 158 to 1, and fuzzball was able to start.  I then started, did at-shutdown, and voila, minimaldb was made again.
I want to figure out how to make the smallest minimaldb possible, but UNTIL THEN, this at least makes all sysparms show up as [default] when they are default.  That is a good success.
I do realise some extra props are at the bottom.
Onward to trueminimaldb!
> Regenerate minimaldb

- docs/index.html
I realised it's not WEB documentation for anyone just viewing it after unzipping the .tar.gz, and that the mpi-intro files and muf-tutorial files were never specifically web documentation.
> Minor nitpick in index.html wording

- src/set.c
This also fixes _do_unlink's doxygen comment.
There shouldn't be any functional change here.
> _do_unlink's quiet is now a bool

- docs/index.html
This, semantically, is more correct in HTML.  A parser that can generate outlines will now produce a better outline for this page.
> Use better tags in index.html

- docs/help.txt
- docs/muckhelp.html
- src/muckhelp.raw
It was adding a spurious H3 element to the html version.  I noticed the MPI and MUF manuals didn't have this blank line, nor that extra H3.
> Remove extra newline in muckhelp.raw

- include/compile.h
- include/edit.h
- include/fbmath.h
- include/fbstrings.h
- include/hashtab.h
- include/interp.h
- include/mcpgui.h
- include/move.h
- include/msgparse.h
- include/mufevent.h
- include/player.h
- include/predicates.h
- include/props.h
- include/timequeue.h
The goal of these diffs is to get more includes into the files they belong in.  This is in preparation for using iwyu, https://include-what-you-use.org/ to help us move standard C header includes out of config.h and into the files they belong in.
These results come from me applying the automatic fixes from iwyu and seeing what broke, and fixing what broke.  (no!  this pull request does not include the automatic iwyu fixes.  those will come in a second PR)
> Fix up includes a bit, part 1 of 2 or more

- include/crt_malloc.h
- src/compile.c
- src/crt_malloc.c
- src/set.c
This has the documentation for crt_malloc and also for a few other things, mostly things @nyanster found in past PR's.
I removed all the weird emacs markup code.  I think that was for some function indexing feature that is now common in most modern editors without weird markup needed.  I haven't seen that any place else (even in any other project) so I doubt its a commonplace need :)
> Continue docs - crt_malloc

- docs/changesfb7
Out of a courtesy to users who will have a huge pile of text fly into their screen.
I noticed previous changesfb* files have one or multiple blank lines at the bottom.
> Add blank line to changesfb7

- include/config.h
- src/compile.c
- src/interface.c
- src/interface_ssl.c
- src/resolver.c
- win32/win32.h
I removed all the includes that weren't under ifdefs, EXCEPT
stdlib.h is used in config.h in relation to RANDOM
TODO: move that include to a fbmuck.h file
better TODO: get rid of our random-related ifdefing and defining, if possible.
Includes were also added as needed.
TODO: figure out what includes we can remove elsewhere.  I've added a lotta includes, but this is the first time I've removed any.
This PR is 100% safe though, to my knowledge.  Tested on FreeBSD.  Interested in Travis and AppVeyor results.
> Remove most includes from config.h

- configure.ac
- include/config.h
OSes without arc4random() will use rand()
The usage of arc4random_uniform() with that argument is to guarantee the results have the same range as rand().
arc4random() has no seed function, so we just call srand(), which does not affect arc4random()'s results.  Hey, won't this affect behavior?  The answer is actually no!  SRANDOM() is only ever called once, with a seed of getpid(), meaning repeatability wasn't even desired there.  In the code, only actual srand() is used when a deterministic PRNG is desired.
I've found both rand() and RANDOM() in the code, but not random().  That's a portable mix, already.
I also correct my TODO comment:
I realise it may be necessary to keep stdlib.h here as long as we have our HAVE_RANDOM/HAVE_ARC4RANDOM_UNIFORM ifdef.
I want to get rid of the ifdef, …
> Switch from random() to arc4random()

- src/Makefile.in
-l flag ordering is actually important to cc.  While both the before-this-diff and after-this-diff work, this organises the unix/posix libraries before the third-party libraries
This is optional, but I feel it achieves better clarity.
> Do a small linking re-ordering

- dbs/advancedb/data/advancedb.db
This better matches our time info elsewhere, and is useful info anyway
> add time zone info to mpi uptime

- dbs/advancedb/data/advancedb.db
- dbs/advancedb/muf/86.m
This is a no-no.  The status prop isn't protected in any way at all, so anyone can set themselves to have the WIZ status.  That's fine, but it shouldn't be given its own color in ws.
This should make impersonating a wiz by accident or on purpose less likely.
Documentation is also fixed in this PR.
> Remove colorisation of WIZ status

- include/commands.h
- include/compile.h
- include/config.h
- include/crt_malloc.h
- include/db.h
- include/fbmuck.h
- include/fbstrings.h
- include/interface.h
- include/props.h
This is the first of likely many things that can be moved out of config.h, as it is not meant to be configured, neither by user nor by autoconf.  As the dbref typedef is pretty generic, I give it its own generic/miscellaneous header file.
The define is intentionally FBMUCK_H and not _FBMUCK_H
Having defines start with an underscore isn't a good idea.  I believe they're reserved for C implementations, and I can double-check on that if necessary.
TODO: change our current defines to not start with an _ underscore.
potential TODO: see if it's possible to have the MUCK not break when dbref is typedef'd to a different type.
> Move dbref typedef to fbmuck.h

- include/interface_ssl.h
- src/interface_ssl.c
The only thing I could find about triple-slash comments is Doxygen might pick them up, however, the things these triple-slash comments are above in interface_ssl.h, I'm not sure whether Doxygen can (or usefully can, as these are very simple descriptions) document.
@tanabi , what do you think?
If you want to convert some of these to Doxygen comments later by doubling the first asterisk, that's all fine. :D
Also, I see in the code and comments that we already have some code that uses OpenSSL 1.1.0+ features if available...  But not if not available.  Just thinking about OpenSSL version stuff.
> Style nitpick in interface_ssl.[ch]

- src/mkversion.c
> include strings.h in mkversion.c

- src/wiz.c
POSIX labeled getpagesize() as legacy a long time ago, and later removed it.  But while it was still there, but labeled as legacy, it defined it as identical to sysconf(_SC_PAGESIZE), other than for the result being a long rather than an int.
I need help with this one.  This can't be merged yet, but I don't know why things are differing.
Before:
```
Process ID: 2237
Max descriptors/process: 233379
Performed 0 input servicings.
Performed 0 output servicings.
Sent 24 messages over a socket.
Received 3 messages over a socket.
Received 0 signals.
Page faults NOT requiring physical I/O: 183
Page faults REQUIRING physical I/O: 0
Swapped out of main memory 0 times.
Voluntarily context switched 10 times.
Involuntarily context switched 0 times.
User time used: 0 sec.
System time used: 0 sec. …
```
> Switch from getpagesize to sysconf

- include/defaults.h
- include/fbtime.h
They're only used in `defaults.h`.  I personally think the readability required is done better via good commenting than via macros.  It also reminds users that the final value genuinely is in seconds, and they can use any number of seconds they want.
We also save a few steps of multiplication, though that's not the impetus here.
If you think this is a bad idea, let me know!
I also chose to align everything. (with spaces, of course)
I also added a blank line to emphasise that PNAME_HISTORY_REPORTING is a boolean, not a time.
> Remove TIME_MINUTE/HOUR/DAY macros

- src/interface.c
- src/resolver.c
There are types meant for addresses and ports.  The IPv6 code was typically more correct than the IPv4 code, fixed both though.
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/netinet_in.h.html
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/inttypes.h.html
I also did some style fixes.  Not to the entire files, but to the portions I already touched.
I then removed an incorrect cast.
> Use appropriate types for ports/addresses (attempt 2)

- src/resolver.c
When fb-resolver tries to return -1 to the shell, my shell interprets/receives it as 255.  We can't expect any particular number in a portable way, though, when returning a negative number to the shell.
I change it to 2, which the shell receives as 2.  I did this because exit(1) is already used in main(), and I wanted to keep the exit numbers for these two situations different for now, as they were already different.
I've also checked prochelp (prochelp.c) and fbmuck (interface.c) and didn't spot any cases where they might attempt to return a negative number to the shell.  (though the win32 restart program does, but I'm not touching it)
I've also already checked for this in all our shell scripts, in the past.
> Fix exit code for fb-resolver

- game/restart.in
Don't exit 0 (EXIT_SUCCESS) in failure conditions.
I decided to give the three exits here different numbers for now: they can be condensed into a single number if required, later, but that's highly unlikely.
> Fix exit codes in fb-restart (restart.in)

- dbs/advancedb/muf/56.m
- dbs/basedb/muf/30.m
They were using different versions to begin with.  These both now have the fix from fuzzball-muf
> Fixed basedb and advancedb copies of cmd-mv-cp

- src/timequeue.c
@wyld-sw I know you're a merge-happy crazy-guy :)  so please read this first.
While I am .... 95% confident I've fixed this (I would be 100% if I understood the code a bit better), I may have introduced a (rare) memory leak.  I marked it with a big TODO ... There's a difference between dequeue_prog_real and dequeue_process (which underpins @ kill) that I don't really understand and I'd like your opinion on.
If you're just as clueless as me, I think we may need to do "something" to verify there's no leak.  Probably the easiest way to do this is to connect a bot to a test MUCK and have it enter @ edit on a event_wait MUF and just hit 'c' endlessly to see if the memory increases.
As I re-read this block, I'm thinking it may be something that won't be possible if we delete event queue before …
> Fix for the dreaded #306 segfault

- src/array.c
It seems that 3b228ce introduced a crasher bug when the `array_insertrange` function was cleaned up. The `TODO` lines that said that something was impossible, didn't take into account the side effect that `array_first(inarr, &idx)` had on the `idx`. Coincidentally, it also reset the `idx.data.number` back to 0 as part of the call, resetting the loop for the next step of copying in `inarr`. 
This likely wouldn't have been a huge deal in some cases, but in the case that produced the crash, it happened when `run peak` is executed, where `peak` is an alias to `nexus,w,w`. The muf program eventually ends up with a call stack of `#0 'peak' 'nexus' [] 0 ['w', 'w']`. This ends up calling `array_insertrange([], 0, ['w', 'w'])`. The loop that copies over the first array is skipped because …
> Fixed crasher bug introduced by 3b228ce

- src/create.c
- src/db.c
- src/p_db.c
This is my first pull request ever so I'm hoping I'm doing it right.
In addition to setting the default thing value to 0 instead of 1 as discussed in issue #459, there was a bug where if you are an unquelled wizard and you do: @link action= without specifying any destinations, it will increase your pennies.
Also I added a safety check to @create and @clone that prevents it from creating an object with a negative value.
> Change default thing object value to 0

- src/db.c
Fixes this:
```
> @create test=0=a::b
Object test(#190) created.
Now registered as _reg/a::b: test(#190) on Mercury(#164PWQBC)
> ex me=_reg/
- ref /_reg/a:test(#190)
1 property listed.
```
> Fixed check for valid property name when registering objects

- src/create.c
- src/set.c
Fixes two things:
- `@link unclaimedexit=room` when you don't have a BUILDER does not work, but it was charging you the pennies /before/ rejecting the attempt. I reversed this, checking first before charging.
- You have to pay tp_exit_cost pennies when you do `@link unclaimedexit=room`, but you could cheat and get around this by doing `@chown` unclaimed exit. I copied the logic for charging you pennies from `@link` into `@chown`.
IMHO though, I think that long term, the entire 'anybody can seize an unclaimed exit' thing should be eliminated from fbmuck entirely.
- I can't imagine any MUCK out there using this functionality. (Correct me if I'm wrong?)
- It can easily be replaced in a more robust and intuitive way by creating a MUF program to claim/create exits.
- It's a security risk, in …
> Pennies related fixes to @chown and @link when dealing with unlinked exits

- src/set.c
Should only be charging pennies for the exit, not link + exit in do_chown (because no linking is happening).
> Fixed oversight in previous commit

- src/p_db.c
SETLINKS was able to link to NIL, but not SETLINKS_ARRAY. Fixed.
<hr>
\<rant\>
This looks like a bug caused by large blocks of nearly-identical code being in multiple places in the source, and when a modification happens, forgetting to replicate the same change to other bits of the code.
It actually seems pretty common for big chunks of code with very similar logic to be just copied with small modifications all over the source. Might be worth going through and fixing that up.
One nuclear option to fix a big class of this code duplication problem (which I would actually be in favor of) would be to eliminate the built-in commands entirely and replace them all with MUF programs (with the exception of `@program` and probably some limited emergency commands in case you mess up `@action` or …
> SETLINKS_ARRAY can now link to NIL

- src/db.c
Since fbmuck prevents 'me' 'here' and 'home' as object names because they are special matches, 'nil' should probably be added here as well.
> 'NIL' probably should not be a valid object name

- src/p_db.c
The COPYOBJ primitive duplicates the contents of the database object, but leaving a pointer to the previous properties tree in tact. Then it calls copy_prop which (I believe) makes a new property tree structure for the object and copies the previous one.
However, in the meantime, while the pointer for the property tree for both objects is still set to the original object, it does `SETVALUE(nu, 1)` which acts on the shared pointer (because the object's penny value is inside the property tree... I'm guessing it wasn't always this way) and sets the value of both objects to 1.
I don't know if I've addressed this correctly, though. Before merging this change... should I still be setting the object's penny value?
This pull request as written will copy the penny value exactly. Whatever the …
> COPYOBJ was setting the penny value of _both_ thing objects to 1

- src/match.c
YIELD was working for child rooms, but not working if you were standing directly inside the room with the flag set.
> Fixed YIELD not working when set on current room

- docs/man.txt
- docs/mufman.html
- include/tune.h
- include/tunelist.h
- src/game.c
- src/interface.c
I'd like to add this tune because I want to use it on my own MUCK for security and cosmetic reasons, and because it seems like a good intermediate step toward some day removing built-in commands entirely.
I've also created a repository (https://github.com/dbenoy/mercury-muf) where I'm working on MUF replacements for built-in commands, among other things. I've created copies of the logic for the object creation commands and followed the engine source fairly closely.
For various reasons the commands won't have precicely the same message output, but they try to follow the behavior of the built in commands in a quirk-for-quirk way.
It also adds a few features like object quotas, but I intend, once these programs are fairly well tested in the wild, to create a separate repository with vanilla …
> A @tune to prevent built-in commands (Except for wizards with !override)

- include/commands.h
- scripts/teledump-extract.py
- src/game.c
- src/wiz.c
This commit adds a command called '''@teledump'''.  The purpose of this is to dump the MUCK DB, macro file, and MUF files to the calling player's screen.  It is, of course, restricted to wizards.  This is for the implementation of "MUCKs as a service" to provide users a way to get their MUCK databases without having to have shell access.
The format it dumps in is kind of weird, so I have included a Python script called teledump-extract.py which (in my testing) totally reconsitutes the MUCK with 100% accuracy.  Pretty cool!  I need to test this on a bigger DB to make sure there's no gotchyas that I haven't found yet, but, I'm at least confident this won't crash fuzzball if used.
> Added teledump feature

- include/fbtime.h
- include/interface.h
- src/fbtime.c
- src/interface.c
- src/wiz.c
This fixes the missing lines from teledump and also provides a way to output stuff from Fuzzball without the fear of <Output Flushed> messages.
> Made it possible for Fuzzball to transmit large amounts of data without truncation

- include/mcp.h
- src/mcp.c
- src/mcppkgs.c
@revarbat  seems to be finding a lot more of these bugs than I am -- there are some calling patterns like this:
```
lines = mcp_mesg_arg_linecount(msg, "data");
for (int i = 0; i < lines; i++) {
/* Any mcp_mesg_arg_getline for "data" in this loop should be safe, right? */
}
```
So Revar may be adding checks in there which I am not sure are necessary.  However, I would appreciate additional sets of eyes on this.
Fix for: https://github.com/fuzzball-muck/fuzzball/issues/510
> Mcp crash fix

- src/mcppkgs.c
- src/p_mcp.c
For https://github.com/fuzzball-muck/fuzzball/issues/510
> Corrected some places where segfaults can occur if MCP is called via the login screen instead of being logged in.

- src/p_connects.c
An 'else' in prim_descr_array() was removed in b09e0064, causing segfaults on '#-1 DESCR_ARRAY'.
> Fix DESCR_ARRAY crash

- src/log.c
If it's not possible to open the log file, then vlog2file() has code to log to stderr instead, but it still tries to use the NULL returned file pointer in that instead.
> vlog2file: do not use NULL FILE*

- include/interface.h
- src/interface.c
This patch adds an option -console on non-Windows platforms to treat stdin and stdout to the server as if it were a connection. If this connection QUITs or is booted, it is restarted. When the -console option is specified, -nodetach is implied and, if no port numbers are specified, the server starts with no listening network sockets instead of the default of a non-SSL listening socket on port number 4201.
I hope this option will allow for practical automated tests of the Fuzzball server, but it may have some other uses, too.
The option is disabled on Windows because my understanding is that getting file descriptors that behave sufficiently like sockets to a console is more involved on Windows.
> add -console option to treat stdin/out as connection

- src/set.c
The restricted() function should return true when setting the flag is restricted, so the original check made it so #1 couldn't set the QUELL flag at all.
> Fix inverted God check for QUELL flag.

- src/crt_malloc.c
Some code can call free(NULL), which is not an error (it's defined to do nothing), but CrT_free (used when memory profiling is enabled) may try to dereference the NULL pointer in this case.
> CrT_free: ignore free(NULL)

- src/match.c
noisy_match_result uses notifyf when it doesn't pass a format string.
(This was probably a security vulnerability since, e.g., `@dig Bad=%n%n%n%n%n%n%n` caused a crash from it.)
> do not use notifyf for non-format-string message

- src/interface.c
interface.c:2075:9: warning: unused variable 'i' [-Wunused-variable]
int i;
^
interface.c:2141:9: warning: unused variable 'i' [-Wunused-variable]
int i;
^
2 warnings generated.
> fix warnings when USE_SSL is not defined

- src/interface.c
- src/msgparse.c
- src/prochelp.c
I renamed the inner variables to solve the conflict.
cc -O2 -pipe -W -Wall -Wshadow -Wno-unused-parameter -Wno-sign-compare -std=gnu99 -fwrapv -I../include  -I/usr/local/include -I/usr/local/include  -c prochelp.c
prochelp.c:680:9: warning: declaration shadows a variable in the global scope [-Wshadow]
int topichead = 0;
^
prochelp.c:159:26: note: previous declaration is here
static struct topiclist *topichead;
^
prochelp.c:842:31: warning: declaration shadows a local variable [-Wshadow]
for (replacement *temp = replacements; temp->token; temp++) {
^
prochelp.c:684:10: note: previous declaration is here
char temp[BUFFER_LEN];
^
prochelp.c:875:9: warning: unused variable 'cols' [-Wunused-variable]
int cols;
^
3 warnings generated.
> fix variables that shadow others

- include/commands.h
- include/compile.h
- include/interface.h
- include/props.h
- src/array.c
- src/boolexp.c
- src/compile.c
- src/debugger.c
- src/edit.c
- src/interp.c
- src/mufevent.c
- src/p_db.c
- src/p_mcp.c
- src/property.c
- src/props.c
Was randomly looking through the bazillions of warnings we have with `-Weverything`, and `-Wdocumentation` caught my eye. I'm relatively new to doxygen, so let me know if there are things I've done that are silly or make things worse!
I have not addressed any`-Wdocumentation-deprecated-sync` warnings - and like this update, it's probably very far from urgent.
> Attempted some -Wdocumentation warnings cleanup.

- src/p_misc.c
- tests/command-cases/p_misc.yml
Add null pointer to checks to convtime, fmttime primitives to prevent crashes when they are called with empty strings.
Also add some tests that would trigger the crashes.
> add null pointer to checks to convtime, fmttime primitives

- src/p_math.c
- tests/command-cases/p_math.yml
- tests/test_util.py
prim_plusplus and prim_minusminus assumed MAX_VAR was the maximum index of a variable rather than the maximum number of variables, so they're check was off-by-one. This caused an out-of-bounds access into the variables/local-variables arrays.
I also notices that the scoped variable check was based on the variable number rather than whether scopedvar_get() returned a null pointer (though I'm not sure whether this could actually cause a NULL pointer dereference).
Also added some tests of this part of the ++/-- functionality (regressions for the out-of-bounds accesses and tests of normal behavior) and adjustments to the tests to be better at outputting stderr when the MUCK crashes.
> fix off by one error in prim_plusplus/minusminus; add related tests

- src/mcpgui.c
- src/p_mcp.c
- tests/command-cases/p_mcp.yml
Via some fuzzing, I discovered that prim_gui_value_set tries to call free() on an uninitialized pointer when it is passed a dictionary-like array instead of a list-like array. This fixes that, triggering an abort_interp() in that case.
In the process of testing this, I also noticed that GuiFree() failed to free dialog control tracking structs fully.
This patch also adds a couple tests for gui_value_set. This includes some hard-coded MCP messages to make the mcpgui code believe that it's talking to a client that supports the MCP GUI stuff.
> Fix memory errors in prim_gui_value_set, GuiFree

- src/p_array.c
- tests/command-cases/p_array.yml
Add a check that the array passed to array_notify has valid objects. Also include the M1 object-is-remote check. Previous code would access out-of-bounds when an invalid dbref like `#-1` was passed in the dbref array.
Also add corresponding tests.
> Check validity of dbref array passed to array_noitfy

- include/interface.h
- src/create.c
- src/look.c
- tests/command-cases/create.yml
- tests/command-cases/look.yml
do_look_at and do_program both used notifyf_nolisten with the result of something like match_msg_ambiguous, which is not a format string and might contain %.
Also add tests to diagnose these cases.
Also modify interface.h's declarations of notifyf and notifyf_nolisten to add the "format" function attribute for GCC and clang, so they will give warnings about this issue with -Wformat-security.
> Fix several instances of notifyf being used without format string; mark notifyf functions for compilers

- src/p_regex.c
- tests/command-cases/p_regex.yml
The MUF primitives REGSPLIT and REGSPLIT_NOEMPTY do not advance their position in the input string when the supplied regular expression matches an empty string. This means that something like "FOO" "|" regsplit results in essentially an infinite loop.
This fixes this by making sure that REGSPLIT always advances their position in the string by at least one character, including a special case for when this is how the last character in the string is covered.
Also add some tests for REGSPLIT and REGSPLIT_NOEMPTY that exercise this functionality.
> avoid infinite loop in regsplit when regex matches empty string

- src/p_stack.c
- tests/command-cases/p_stack.yml
- tests/test_util.py
When given a pattern like "{}", the CHECKARGS primitives will execute a loop in C for a number of iterations specified by the number at the top of the stack, allowing an unpriviliged MUF program with code like `1000 1000 * 1000 * "{}" checkargs` to make the server hang for a while. The code properly checks for a range of that number of copies of nothing on the stack.
This fixes that issue by special-casing "{}", "{ }", etc. in prim_checkargs. Other patterns should require at least one item to be examined on the stack in the range, limiting the number of iterations to the depth of the stack, which is bounded more reasonably.
This also adds a bunch of tests (but by no means tests sufficient for complete coverage) for CHECKARGS, and modifies the tests to support timeouts.
> Avoid very long loops in prim_checkargs; add tests for checkargs

- include/array.h
- include/interp.h
- src/array.c
- src/interp.c
- src/p_misc.c
- src/p_stack.c
- tests/command-cases/p_array.yml
- tests/command-cases/p_stack.yml
By recursive arrays I mean arrays which contain pinned arrays that contain themselves
(directly or indirectly). Trying to copy these naively as deep_copyinst used to causes infinite recursion.
Previously deep_copyinst couldn't fail. This patch changes that and modifies prim_deep_copy
to expose the failure as a MUF error. deep_copyinst is also used by prim_fork. This patch
does not modify prim_fork.
When deep_copyinst fails it modifies the destination into the integer '0' to limit problems
from later use of this copy. (CLEAR() might be a better choice at least after prim_fork is
cleaned up to be aware of deep_copyinst failing.)
Also add basic tests for recursive array scenarios and normal usage of the deep_copy primitive.
> Modify deep_copyinst to fail when copying recursive arrays.

- include/commands.h
- include/mufevent.h
- include/props.h
- src/array.c
- src/compile.c
- src/create.c
- src/db.c
- src/edit.c
- src/fbmath.c
- src/fbsignal.c
- src/game.c
- src/help.c
- src/interface.c
- src/look.c
- src/mcp.c
- src/mfuns2.c
- src/p_mcp.c
- src/player.c
- src/property.c
- src/sanity.c
- src/set.c
- src/speech.c
- src/timequeue.c
- src/tune.c
- src/wiz.c
- bad-function-cast
- conditional-uninitialized
- documentation-unknown-command (*)
- float-conversion
- format-security
- missing-noreturn
- missing-prototypes
- newline-eof
- static-in-inline
- unreachable-code-break
(*) Warnings addressed were related to @-commands in docblocks.
> Addressed a few compiler warnings:

- README.md
- README_UNIX.md
- README_WINDOWS.md
- appveyor.yml
* Bundle `README.md` and `README_WINDOWS.md` in Windows builds
* Save as `.md.txt` with Windows line endings
* Generate `.md.htm` HTML files via PowerShell
* Move AppVeyor builds to Visual Studio 2019
* Needed to get PowerShell 7.0 on AppVeyor, used for Markdown rendering
* Make `README` Markdown easier to read as plain text
* Inline URLs for easier access
* No difference to rendered view
* Move `Running` section on Windows to top
* Clean up Windows build artifact
* Add `win32` source directory since other source is already included
* Remove `restart.in`, only used on Unix
Impact | ★☆☆ *1/3* | Provides better guidance for using Windows builds
Risk | ★☆☆ *1/3* | VS 2019 changes, larger artifacts, Markdown render bugs
Intrusiveness …
> ci: Move Windows to VS 2019, add rendered README to build artifact

- src/interface.c
Also, slightly refactored WHO processing in do_command to:
- fix a pointer error with !WHO that treated the command as "@WHO O"
- stop recognizing !WHO on the welcome screen.
> Fixed last commit that caused a crash on the welcome screen.

- Dockerfile
- README_DOCKER.md
- docker-compose.yml
- scripts/docker-entrypoint.sh
- Make builds independant of the OS the container runs on
- Leverage tinit to allow better process handling
- Support non-default kill signals for the fbmuck process
- Update documentation
> Clean up docker container implementation

- Dockerfile
Fixes @skylerbunny 's PR using local files to build instead of pulling it down from GIT.  The build is actually still pretty fast so even though I feel like I might be able to make this more efficient (using volumes or whatnot) I don't think its worth the trouble.
> Fixed docker to build based on local source files

- Dockerfile
- Makefile.in
- include/interface.h
- include/p_connects.h
- src/interface.c
- src/mfuns.c
- src/p_connects.c
@wyld-sw 
Okay I think this works -- WHO now shows people in the right order, and this gets rid of the whole connection table.
What I'd like to do before merging this is really test the hell out of this, especially I want to test all the MUF primitives for similar behaviors.  i.e. for instance first descriptor / last descriptor.  However I think this is good enough to code review.
Feel free to merge this into condescr branch, should be safe to do so, it won't touch master.  Feel free to help trace and test :)  This is kind of a big one so the more eyes won it the better.
> Alterations to condescr branch

- src/p_connects.c
This fixes bugs in DESCR_ARRAY, ONLINE, and ONLINE_ARRAY that weren't caught in #655. To demonstrate:
```forth
: main
#-1 descriptors debug_line popn
#-1 descr_array debug_line pop
online debug_line popn
online_array debug_line pop
;
```
It also fixes ONLINE and ONLINE_ARRAY returning multiple dbrefs for players that have more than one descriptor connected and logged in. This was inadvertently introduced when migrating from the "connection" list to the descriptor list.
Regarding my comments in d1de0a9, I'm honestly unsure whether to replicate the original undocumented behavior. I don't know of any code that uses it besides one program from Nameless MUCK, which sorts the connection list itself anyway according to user input. If you'd like the old behavior back, just say the word.
> More condescr fixes

- src/p_connects.c
Additionally, it didn't always check whether the descriptor was valid. Not
strictly a huge defect, but you shouldn't be able to run `-1 "" DESCRNOTIFY`
and *not* get an error.
> Fix possible uninitialized var in DESCRNOTIFY

- src/p_array.c
Two itty bitty changes:
1. Take care of the TODO in ``prim_array_get_propvals``, which the doc comment claimed was already implemented; and
2. Pull the check capping the returned array in ``prim_array_get_proplist`` out of the loop.
> Tiny fixes

- docs/help.txt
- docs/muckhelp.html
- include/commands.h
- src/game.c
- src/muckhelp.raw
- src/wiz.c
* Changed some [un]bless logic: The strict_god_priv check happens outside the loop, and unbless includes that check now, and both use buffers spaced to avoid warnings for the response.
* Changed usage output to expect larger number ranges.
* Refactored profiling command set into one command - `@tops`:
- This command now has an optional parameter [muf|mpi] that can switch to the corresponding logic.
- This is mostly moving logic around, so any profound updates (stop reading the entire database, stop sorting linked lists, etc.) have not been made.
- I believe there were some (more) issues in the original code as a result of copying into the other two commands. The last line of output in particular can show over 100% idle time and the "profile length" only seems to be reset when you "reset" …
> wiz.c changes

- src/interp.c
Fixes a bug introduced way back in e35d6543 -- `buf` was no longer being written to, so `.debug/lasterr` wasn't getting written properly.
> Fix MUF error messages not logging to .debug

- docs/help.txt
- docs/man.txt
- docs/mpihelp.txt
- include/config.h
Unsure whether to make a this a pull request, an issue ticket, or a comment on the original commit, especially since I'm 2 years after the fact. Feel free to critique.
The new version number format, as of 1ee836a4, sorts _before_ previous version numbers. It also breaks the promise in `man __version` that `__version` will always start with `Muck2.2fb`. Granted if the old license isn't in effect anymore the version number doesn't _have_ to start with anything, but given that it breaks every version comparison ever written, I think this is a pretty major change.
> Revert to old version format

- docs/man.txt
- docs/mufman.html
- include/tune.h
- include/tunelist.h
- src/interface.c
- src/p_db.c
- src/tune.c
Kinda sorta responds to #620.
Abusing {&cmd} and {&arg} to store descriptor and hostname feels bad, but you can't define MPI variables from outside of do_parse_mesg and since the only player we have is One (or whoever welcome_mpi_who is) it's the only information we have to work with.
> Add MPI parsing to login screen

- src/game.c
- src/interface.c
- src/interp.c
As mentioned in 6943e5af, this doesn't do much for the bulk of the compiler warning spam -- some of which I don't think is possible to reduce.
> Minor bug and compiler warning fixes

- include/db.h
- src/db.c
- src/player.c
- src/sanity.c
- tests/command-cases/player.yml
This addresses issue #680.
I added a couple very simplistic tests based on `create.yml` in `player.yml`, which could probably stand to be expanded-upon, but the perfect is the enemy of the good. Similarly, I was very tempted to try to use `<stdbool.h>` (and define `bool`, `true`, and `false` in `config.h` if it wasn't available), but decided modifying `configure.ac` was a step slightly too far.
> Modify new_object to take a flag, so players don't get old refs.

- src/edit.c
- src/interp.c
...to "Unable to compile [[UNPARSED_OBJ]]." in the following contexts:
- viewing public words within the editor
- directly invoking a program
- calling a program from another context (propqueue / other program)
I did not test writing to the muf_errors log, as the related issue mentioned. My understanding is that do_compile takes care of writing to that log, but the "unable to compile" message happens after that.
> Clarified "Program not compilable..." message 

- docs/man.txt
- docs/mpihelp.html
- docs/mpihelp.txt
- docs/mufman.html
- include/interface.h
- include/mfun.h
- include/p_connects.h
- src/interface.c
- src/mfuns.c
- src/mfuns2.c
- src/mpihelp.raw
- src/mufman.raw
- src/p_connects.c
This resolves #424 
Allows the MUCK to get terminal size from telnet protocol, and provides both MUF and MPI prims to take advantage of them.  Also makes MPI right/left/center use introspected screen size if available.
> #424 Terminal Size introspection implementation

- dbs/starterdb/muf/34.m
Starterdb's wf is actually slightly different from the fuzzball MUF repo's wf and I believe it is to avoid the use of a macro that is present in the fuzzball MUF repo's version.  Good thing I checked the diffs before committing :)  It might be a good idea to copy the starterdb's wf to fuzzball MUF's for consistency sake or vise versa based on what makes the most sense.
However, that's more investigation than I want to do right now and I'm not sure it matters enough to put an issue in for it, since 99% of people will just get laston from starterdb and never look at the one in the fuzzball MUF repo.
>  Update starterdb wf with bugfix applied to fuzzball muf 

- include/mfun.h
- src/boolexp.c
- src/edit.c
- src/fbsignal.c
- src/interface.c
- src/interp.c
- src/look.c
- src/mfuns.c
- src/mfuns2.c
- src/move.c
- src/p_connects.c
- src/p_db.c
- src/p_stack.c
- src/player.c
- src/prochelp.c
- src/resolver.c
- src/sanity.c
- src/wiz.c
- implicit-fallthrough
- type-limits
- switch
- unused-paramater (in fbsignal)
- misleading-indentation
- unused-variable
- unused-but-set-variable
- old-style-declaration
> Address several compiler warnings (some pedantic).

- src/game.c
- src/set.c
A little redundant in order have the guest-check near the beginning, but "set" and friends are screaming for a refactor anyway.
> Move guest-check inside do_set, and allow general wizards to un-guest.

- dbs/minimal/data/minimal.db
- dbs/starterdb/data/starterdb.db
- include/config.h
- include/db.h
- include/player.h
- include/tunelist.h
- src/create.c
- src/db.c
- src/fbstrings.c
- src/fbtime.c
- src/interface.c
- src/interp.c
- src/mcp.c
- src/p_db.c
- src/p_mcp.c
- src/player.c
- src/resolver.c
- src/timequeue.c
- src/wiz.c
This places name sanity checking closer to the point of object creation, so it can be used in all caller contexts. Player passwords are also checked in this way.
Commands affected are `@action`, `@clone`, `@create`, `@dig`, `@mcpprogram`, `@open`, `@pcreate`, `@program`, and `create` on the login screen.
Primitives affected are `COPYOBJ`, `COPYPLAYER`, `NEWEXIT`, `NEWOBJECT`, `NEWPLAYER`, `NEWPROGRAM`, and `NEWROOM`.
**Techniques**
- Passing error messages with a string pointer. Seems like an old-style idea, so let me know if there's a more preferred way. It could eventually be an error struct...
- SMALL_BUFFER_LEN = ~100~ 128. I didn't want to use another huge chunk of space for this. ~100~ 128 may be flexible enough for now - I was able to use it in several other places where buffers …
> Unifies basic sanity checks for object creation.

- include/interp.h
- src/p_misc.c
This cleans up most of the TODOs in p_misc.c.
**Global variables**
Variables for temporary ints, dbrefs, string buffers, and timestamps have been moved into the functions using them. The inst pointers "oper1" through "oper4" are currently ALL needed for the abort_interp macro. A TODO has been placed in interp.h for this.
**Code consolidation**
- Some operand sanity checks were combined when it made sense. Most of these are of the form "must be a valid object" and "must be a certain object type". 
- The DoNullInd() macro was used one place it was suggested, but the other could not be (due to its argument needing to be a certain type).
- `EXT-NAME-OK?` now uses strcasecmp() instead of lowercasing the type string beforehand. I'm not sure of the performance impact , as the possible "good" …
> TODO cleanup: p_misc (mostly)

- include/db.h
- include/props.h
- src/boolexp.c
- src/look.c
- src/mfuns2.c
- src/p_db.c
- src/predicates.c
- src/property.c
- src/set.c
This attempts to combine the locking implementations used in the codebase.
**Reunification**
Most of the lock commands (e.g., `@lock`, `@ownlock`) use set_standard_lock for their implementation. `@unlock` and `SETPROPSTR` did not; this is now corrected.
**CLEARLOCK, GETLOCK, and SETLOCK**
These macros were used for the main object lock only; they are now extended to act on any type of lock.
CLEARLOCK now removes the property (instead of setting it to TRUE_BOOLEXP) as other mechanisms do. It also continues to update an object's modification time.
GETLOCK can now be used in all cases that get_property_lock was called directly. Is it redundant? Probably - but then so are  lot of other GET* macros.
SETLOCK is now used in the refactored \_set\_lock (discussed below). It also continues to …
> Unifies setting and clearing lock properties.

- src/p_error.c
- src/p_float.c
- src/p_misc.c
**Non-cached `GAUSSIAN`**
The current `GAUSSIAN` caches one of the generated random numbers for a potential next call, as does the traditional algorithm. A comment suggested we may not need to do this, and I would tentatively agree based on my limited testing. Caching does certainly have an impact, but I believe a program would exhaust the instruction limit before that impact is noticeable (even with a much larger instruction limit).
My limited testing included using the undocumented `{timing}` function to loop through several thousand calls (`100.0 5000.0 GAUSSIAN`), with both implementations (with and without caching). Without caching, I hit the instruction limit in less than 0.1 seconds. Now that was just my single-player test server, so I may be jumping to conclusions.
This is mostly …
> Error prim fixes, GAUSSIAN simplification, and style improvements

- include/db.h
- include/mfun.h
- src/db.c
- src/mfuns2.c
- src/p_db.c
This adds an MPI counterpart to the `FLAG?` MUF primitive. The check logic has been extracted into its own function.
**Functionality**
Both MPI and MUF versions check a single flag, which can be a prefix of a flag alias (regardless of object type). The check can also include any number of "!" characters on the left-hand side of the string for alternating negation.
This may be the first object-facing MPI function I've contributed, so let me know if I missed something there.
**Consistency**
This check now recognizes BOUND, HIDE, SETUID, and XPRESS as flag aliases. `SET` also was changed to recognize them.
**Minor change**
The code for `FLAG?` currently:
- allows "" as the flag to check, and eventually returns 0.
- allows "U" as the flag to check, and eventually returns 0.
- does not allow …
> Add {flag?} MPI function

- include/db.h
- src/db.c
- src/fbtime.c
- src/p_db.c
- src/p_error.c
- src/set.c
This addresses p_db.c issues by refactoring sanity checks, moving variables to required scope, and moves to brace-required style for control flow. Please let me know if any of this has unexpectedly modified the logic.
**More errors about errors**
Recent use of snprintf for error messages (and a few stack items) should no longer produce a warning.
**Consistency Crusade** (let me know if these don't make sense to do)
- `ENTRANCES_ARRAY` now requires mlev 3, since `NEXTENTRANCE` does.
- `RMATCH` now strips ansi, since `MATCH` does.
**Need Input**
- Asking for the link of program objects gives an error. A previous maintainer suggested that programs would be implicitly linked to their owner. I could extend that to say that this "home" would be set at creation, and only modifiable through the …
> More cleanup and flag setting refactor - part 1.

- dbs/starterdb/muf/34.m
- docs/man.txt
- docs/mufman.html
- include/fbmath.h
- include/tune.h
- include/tunelist.h
- src/fbmath.c
- src/player.c
This adds a strong hash to the password algorythm re. #46 
Note that, for compatability purposes, it does not automatically rehash the database.  This gives the admin the chance to `@tune tp_legacy_password_hash=true` if they don't want this update for some reason.  Admins that wish to roll this out should advise their players to use `@password` to rehash their passwords.
> #46 Added secure password algorythm

- include/p_db.h
- src/p_db.c
`CONTENTS` should no longer crash when there are no contents. (My last PR caused this).
`CONTENTS_ARRAY` should now return an array with the same mlevel-1 restrictions as `CONTENTS`.
> Fixes crasher and adds mlevel 1 resteictions to CONTENTS_ARRAY.

- dbs/starterdb/muf/18.m
- include/p_db.h
- src/p_db.c
I think this one line fix is all that is needed. lib-editor already had the error logic, but seemed to not clear enough off the stack.
This seems like it works, but please test any uncommon lsedit command patterns if desired.
I'll update fuzzball-muf if this is approved.
Would close #610.
> Fix lib-editor's "invalid line" error logic.

- src/fbmath.c
- src/player.c
This resolves #728 
This works without an issue with my compiler, which is why I didn't catch it.  Since some folks may be already running this version with the password problem, and thus have 128 character instead of 127 character passwords, I made sure the password check mechanism will check based on the length of the hash.
> Fix for buffer overflow issue #728

- docs/help.txt
- docs/man.txt
- docs/mpihelp.txt
- docs/mufman.html
- src/p_db.c
This fixes the bug reported in the fuzzball MUF repo, resolving issue #734
> #734 Fix for findnext bug introduced by me.

- src/player.c
This should at least partially fix #741
It makes sure that the hash of the entered password isn't empty. My assumption is that if the hash isn't zero it should always be a specific length hence a single check for zero length should be enough to fix the issue, if this isn't the case then another check might be necessary.
> Fix for #741

- include/boolexp.h
- src/boolexp.c
Adds BOOLEXP_MPI as a node type for locks, and re-implemented values as a union type (resolves #320).
Adds recursion limit for parsing locks (resolves #86) - currently 50, please change if needed.
This seems to work successfully during local testing, but please review.
> Boolexps: Recognize MPI and limit recursion

- docker-compose.yml
- src/timequeue.c
With fb6.0a33, TREAD was re-coded as an in-server macro.
```
TREAD ( i -- s i )
Acts like a timed READ call.  If the user does not provide input within
the given number of seconds, the READ call will time-out and return a
false boolean, otherwise it returns a true boolean and the string value
entered.  This is implemented as an in-server macro as follows:
"__tread" timer_start { "TIMER.__tread" "READ" }list event_waitfor
swap pop "READ" strcmp if "" 0 else read 1 "__tread" timer_stop then
```
The older logic was never removed. This PR does that.
It also removes "version" from docker-compose.yml since that is apparently deprecated.
> Clean up older timed-read logic.
