fuzzball-muck/fuzzball

- makefile.win
- src/interface_ssl.c
Fixed issues with win32 build after addition of interface_ssl file.
> Ssl interface fixes

- README.md
* Briefly describe Fuzzball and MUCKs in general for those unfamiliar
* Add rudimentary building instructions, including Ubuntu-specific guidance for packages
* Add rough usage directions, enough to get a MUCK server going from scratch
* It's still recommended to read the full directions
* Include links to the official Fuzzball documentation referenced on https://www.fuzzball.org
* Lastly, show off the build status near the top, because we can :)
> Update README.md with rough intro, help, etc

- game/data/help.txt
- game/data/info/muckhelp
- game/data/muckhelp.raw
* Add the ```@credits``` command to help
* Change ```@hashes``` and ```@version``` to include it via the 'also see' remark
Found this command [via the alpha changelog](http://www.fuzzball.org/changelogs/700a1.html).
*I thought I had gotten all of the commands...  So close!  Ah well.  Pardon the minor spam of commits.*
> Update help with @credits command

- src/interface.c
Call WSAStartup before calling make_socket functions. Issue seen when exit(3) is called after socket() returns -1.
This was introduced by 24fd8ea92e14c9d2aa17ce23b9a3a7c936632744 (Improved MUD_ID handling).
I would recommend that you revaluate the order in which things happen due to the changes introduced by MUD_ID. It seems that the MCP init, profiling counters, game init (database loading?), password changes, tune parm loading, and sanity fixes/saves have all been deferred until after setgid and setuid are called. I'm not sure it makes sense to initialize sockets before any of that. Chances are, if you're in a sanity situation, you may quit before accepting connections anyway. Likewise, you can't really connect SSL until after you load the parmfile that has the SSL cert. So, closer …
> Change order of WSAStartup call. Fixes #62 issue.

- src/look.c
I accidentally broke this with my memory leak fixing patch earlier.
> Show parents correctly from examine

- src/p_strings.c
array_fmtstrings calls abort_interp() without first freeing its result array. This patch adjusts all abort_interp calls after the result array is created.
> fix memory leaks in array_fmtstrings

- src/interface.c
This prevents them from leaking into resolver processes (and other processes we might decide to fork+exec).
> Mark sockets as CLOEXEC.

- src/p_strings.c
FMTSTRING had some issues with their logic for CLEAR()ing operand struct insts on errors.
FMTSTRING relied on abort_interp() doing this, but it works based on the value of nargs (set by CHECKOP), and FMTSTRING was using oper2 after having cleared oper1. This meant that abort_interp() would double-clear oper1, triggering an assertion failure when the MUCK was compiled with --enable-debug.
> Fix FMTSTRING oper{1,2,3,4} clearing logic.

- src/p_stack.c
This cooperates better with push/pop depth debugging code.
> replace CHECKOP with EXPECT_WRITE_STACK in prim_lreverse

- src/p_array.c
- src/p_db.c
This should fix some small memory leaks.
> Add several missing CLEARs in p_db/p_array.c

- game/data/man.txt
- game/data/mufman.raw
- include/array.h
- include/interp.h
- include/mufevent.h
- include/p_array.h
- include/p_stack.h
- include/timequeue.h
- include/tune.h
- src/array.c
- src/interp.c
- src/mufevent.c
- src/p_array.c
- src/p_connects.c
- src/p_db.c
- src/p_mcp.c
- src/p_misc.c
- src/p_props.c
- src/p_regex.c
- src/p_stack.c
- src/p_strings.c
- src/timequeue.c
- src/tune.c
Added SHALLOW_COPY, DEEP_COPY, ARRAY_DEFAULT_PINNING.  Documented ARRAY_PIN, and ARRAY_UNPIN.
> ARRAY_DEFAULT_PINNING mods.

- src/p_strings.c
make sure everything defined in color.h is mentioned
> fix attribute tag list in p_strings.c

- game/data/man.txt
Same changes as with the other files.
> Fix attributes list in man.txt

- dbs/advancedb/muf/16.m
also change http to https in the process
> Reduce redirects in links

- src/prochelp.c
The HTML is far more valid now, after changing the defines.  The actual C logic will be changed in the next diff.  In order to help debug this, I'm changing some of the defines into HTML comments: those defines will be entirely deleted in the next diff.
> Improve HTML output (step 1 of probably 2)

- src/array.c
This prevents ARRAY_COMPARE and related MUF primitives from recursing infinitely when presented with a (pinned) array that contains itself, or an array that contains an array that contains itself, like in the MUF programs in issue #200.
This uses a heavy-handed approach of keeping a hash table to detect when the array contains itself. (Maybe there's some less-high-overhead solution?)
> Avoid infinite recursion when comparing self-containing arrays

- game/restart.in
- scripts/fbmuck-add
- scripts/fbmuck-redhat-init
- scripts/fbmuck-sysvinit
I've improved the readability of some scripts. This will make it easier to begin further transforming some of these scripts later. I also fixed some errors: negative numbers cannot be used with exit.
> Modernize scripts (and fix some errors)

- src/set.c
> Removed propqueue check to allow register to set props in any path.

- configure
- configure.ac
Make them positive, since negative ones aren't portable.
> Fix some negative exit codes

- game/data/man.txt
- game/data/mufman.html
- game/data/mufman.raw
- include/fbmath.h
- src/compile.c
- src/fbmath.c
- src/mfuns.c
- src/p_math.c
- src/p_stack.c
Get rid of some custom defines when defines in the standard C library work.  Also fix some documentation.
future directions:
do something about the RANDOM() define, which is defined to either rand() or random()
also, do something about MAXINT in advancedb 86.m whospecies
> Switch to INT_MAX

- src/help.c
Also provide a pull request reference point for future commits.
> Alphabetize help.c includes

- include/boolexp.h
- src/boolexp.c
- src/fbstrings.c
- src/property.c
Not much to say!  Continued work on the documentation project.
> Added documentation for boolexp

- include/array.h
- include/boolexp.h
- include/fbstrings.h
- include/inst.h
- src/array.c
Wow this took a long time.  Brutal :)  But done!
> Added inst.h and array.h/array.c documentation

- include/dbsearch.h
https://github.com/fuzzball-muck/fuzzball/blob/master/src/look.c#L1084
https://ci.appveyor.com/project/fuzzball-muck/fuzzball/builds/22582572#L265
https://github.com/fuzzball-muck/fuzzball/commit/49c9354f704fa9daced63faf52f7910f54eee77b#diff-4274c1f0e4709a8300eccf5d5078aac3R938
This will likely introduce new warnings, which I'll have to check via CI since I don't have access to Windows.  I also fixed minor formatting/alignment. :P
> Fix a warning C4018

- docs/help.txt
- docs/man.txt
- docs/mpihelp.txt
- include/config.h
- win32/autoconf.h
I wonder if there's a simpler way to do this.  Well, I guess for now, version numbers can be dealt with lazily, as this is -master.
> Update last few version numbers

- src/set.c
This fixes #331 - verified on my dev MUCK.
> Fixed #331 - register data leak

- docs/index.html
> Give our GH Pages site an index

- src/sanity.c
it's -> its
Noticed while still reading tanabi's command.h diff.
:B
> Spelling correction in sanity.c

- src/set.c
I think this is OK since there's no at-unlinkquietly command for users.
TODO done. :3
> Remove do_unlink_quiet

- src/compile.c
- src/move.c
- src/set.c
- src/wiz.c
Mostly typo fixes.
I'd like this to be read and approved by @tanabi _before_ this is merged.
:3
> Clean up previous commit

- include/array.h
> array.h typo fix

- src/mfuns2.c
- src/p_math.c
- src/wiz.c
Added them.  They were a lot easier to notice, this time.
> Missed some includes in .c files

- include/db.h
- src/db.c
Here's the docs for db.c
Funny thing that @wyld-sw deleted the inaccurate block describing the DB format.  I deleted that same block and was planning on addressing the matter in this commit message.  My docs technically cover the DB file format, but the details are scattered around in the file now because I document per-function.
I'd say the DB file format would be a good candidate for a wiki item, if we were using wiki.  Randomly jamming it into the code somewhere isn't great.  We could put it in a README-style file I guess.  Or we can just live with it being broken down by function :)
> db.c documentation completed

- include/debugger.h
- src/debugger.c
Pretty straight forward.  Documented debugger.c / debugger.h
> Debugger commented

- include/diskprop.h
- src/diskprop.c
One down, a billion more to go!
> Documentation for diskprop

- include/edit.h
- src/edit.c
Not much to say.  Another monster :P
> Documented edit.c / edit.h

- include/events.h
- src/events.c
> Events.c / events.h work

- include/fbmath.h
- src/fbmath.c
- src/p_misc.c
Much docs, such math!
I didn't put too much effort into documentation for the very stock, copy-and-paste from reference MD5 / base64 code.  It was already well documented at least.
> Documentation for fbmath

- include/fbsignal.h
- src/fbsignal.c
> Documentation for fbsignal

- include/fbtime.h
- src/fbtime.c
Nothing much to say, just another day!
> Documentation for fbtime

- src/edit.c
Found a compiler-variance problem.
> Fixed funky parameter problem

- include/hashtab.h
- src/hashtab.c
Pretty simple, but this thing looks like bait for memory leaks. :)
> Documented hashtab.c

- src/fbtime.c
I want to get this in before updating hope.  I hate 2 digit years :)
> Updated convtime to support 4 digit years.

- include/log.h
- src/log.c
More docs, more fun.  Glad to get an easy one.
> Documented log.h/log.c

- include/match.h
- src/match.c
> Match.c documentation

- dbs/advancedb/muf/56.m
- dbs/basedb/muf/30.m
> Fixed recursive comment

- src/fbtime.c
@wyld-sw  Please give this some test pokes to make sure it looks good.  My test show it works acceptably.  There's probably a better/cleaner way to do this rather than my dumb pseudo-parsing but this is the best I could come up with on short notice.
> Fixed string to time conversion, hopefully forevers.

- include/mcpgui.h
- src/mcpgui.c
Here's the documentation for MCP GUI
I found a method that was declared but not defined so I removed it; normally I put a TODO or put a github issue in since the doc project isn't about modifying stuff ... but in this case the impact seemed low.
> Doc mcpgui

- include/mcppkg.h
- src/mcppkgs.c
> Documented MCP Packages

- include/interface_ssl.h
- src/interface.c
- src/interface_ssl.c
This is a PR to resolve #458 ... to be completely honest I'm not sure it works, I am not sure how to check it :)  I just know the code looks right and it compiles clean.
@whislock will need to check it when merged.  Compile thusly:
```
./configure --enable-force-tls12 --with-ssl
```
(and any other options you want)
> Added force TLS to maximum 1.2 support

- src/move.c
- src/p_db.c
Fixes issue #457
As discussed in that issue, it also brings ADDPENNIES behavior in line with the GIVE command.
> Recycling thing objects with negative value no longer costs you pennies

- include/move.h
- src/move.c
> Documented move.c

- include/mpi.h
- include/msgparse.h
- src/msgparse.c
> Added docs for msgparse

- include/mufevent.h
- scripts/teledump-extract.py
- src/mufevent.c
Merry x-mas!
I also fixed a comment that I left in error.  But mostly this is mufevent documentation.  Lots of TODO's in this one.
> Documented mufevent

- dbs/advancedb/muf/46.m
Before this change, if there were no message props set, the hand/throw message would just show the name of the hander/thrower but nothing else.
This change fixes that, so there's a reasonable default message if no props are set.  It also simplifies the code a bit.
> Fixed the case where there are no message props set on anything - bug reported on Hope Island

- include/p_array.h
- src/p_array.c
Dear lord this took a lot of work.
> Documentation for p_Array completed

- include/p_error.h
- src/p_error.c
Yay this was a quickie!  Enjoying p_db? :)
> Added documentation for p_error

- src/interface.c
Here's a fix for the crash that happens when you toad a player that is currently connected.
> Fix crash bug #495

- include/p_float.h
- src/p_float.c
> Documentation for MUF floats

- include/p_math.h
- src/p_math.c
Woo, another one bites the dust
> Documented p_math

- include/p_mcp.h
- include/p_mcpgui.h
- src/p_mcp.c
And another one gone, and another one gone, and another one bites the dust!
> Documented p_mcp

- include/p_props.h
- src/p_props.c
> Completed p-props

- include/p_regex.h
- src/p_regex.c
> Documentation for MUF regex prims

- include/mcp.h
- src/mcppkgs.c
Hopefully final fix for https://github.com/fuzzball-muck/fuzzball/issues/510
> Refactor to optimize the fix a little bit

- include/p_strings.h
- src/p_strings.c
> Doc p strings

- include/hashtab.h
- include/player.h
- src/hashtab.c
- src/player.c
> Fix a comment in hashtab, documented player

- include/predicates.h
- src/predicates.c
> Finished documenting predicates

- include/p_db.h
- include/p_stack.h
- src/interface.c
- src/p_db.c
- src/p_stack.c
- src/resolver.c
> Documented the resolver

- .cirrus.yml
- src/p_props.c
> Added pemissions checking to PROPDIR? and BLESSED?

- .cirrus.yml
- src/db.c
- src/game.c
- src/interface.c
- src/tune.c
Please check to see if the logic on error conditions is appropriate.
> Acknowledged some return values, addressing compiler warnings.

- include/timequeue.h
- src/p_misc.c
- src/timequeue.c
> Added timequeue documentation

- docs/man.txt
- docs/mufman.html
- include/events.h
- include/game.h
- include/mufevent.h
- include/p_db.h
- scripts/trigger-dump.muf
- scripts/trigger-dump.py
- src/events.c
- src/game.c
- src/interface.c
- src/mufevent.c
- src/mufman.raw
- src/p_db.c
Added DUMP prim, example MUF and Python.
> Added stuff in support of DUMP primitive #537

- src/p_connects.c
Created issues for logic questions.
> Addressed TODOs in p_connects.c.

- src/p_db.c
This fixes a compile error with diskbase.
> #579 diskbase fix

- dbs/advancedb/data/advancedb.db
- dbs/basedb/data/basedb.db
- dbs/minimal/data/minimal.db
- docs/man.txt
- docs/mufman.html
- include/tune.h
- include/tunelist.h
- src/interface.c
Please double check I made the DB corrections right for the new toggle parameter.
> #543 added SSL auto reload

- STYLE.md
First draft of style doc.  I feel like I've been both overly verbose and forgotten things at the same time.  Take a look though!
> #584 added first draft of style doc

- Makefile.in
I forgot this when I made the docker container.
> Fixed it so document files get pushed into the Docker container.

- src/p_misc.c
I'm going to go ahead and merge this since it is pretty crashy :)
> Fixed a segfault that happens if to name is blank

- include/fbstrings.h
- src/create.c
- src/fbstrings.c
- src/game.c
- src/interface.c
- src/mfuns.c
- src/property.c
> Addresses concerns in PR #670

- docs/man.txt
- docs/mufman.html
- src/interp.c
Solves #675 at least temporarily.
> #675 disabled READ when MUF is called from welcome screen

- docs/man.txt
- docs/mufman.html
- include/interface.h
- src/interface.c
- src/mfuns.c
- src/mufman.raw
- src/speech.c
- src/timequeue.c
> #664 simplified listener behavior, improved propqueue documentation

- src/fbtime.c
Man oh man.  I can't believe how easy this way to fix.  It's just a weird obscure devil-in-the-details problem where reading the man page carefully and doing some gdb testing was what it took to fix it.
Resolves #472 ... and completes version 7.1 :)
> #472 fixed CONVTIME finally

- docs/changesfb7
- docs/help.txt
- docs/man.txt
- docs/mpihelp.txt
- docs/mufman.html
- include/config.h
- src/mufman.raw
Added 'man propqueues' change to release notes.
Fixed minor typo.
> Bumped version to 7.1.

- dbs/minimal/data/minimal.db
- dbs/starterdb/data/starterdb.db
+1 to getting these out of the databases in a future database format.
> Adds legacy_password_hash to minimal and starterdb databases.

- src/p_db.c
> Logic error on newobject

- src/interface.c
I'm not a network guy - but this seems straightforward-ish. I've been able to connect with both protocols, but please test and/or suggest improvements.
I haven't included `addrout` and `addrout_v6` in this since they are present in both `interface.c` and `resolver.c` - and I didn't want to inadvertently mess up the resolver. I also wonder if the extra `\n` returned by addrout_v6 is necessary for the resolver protocol - or can be cleaned up (the #670 concern).
> Unify IPv4/IPv6 handling in make_socket and new_connection.

- src/mfuns2.c
- win32/win32.h
Also added typedef for Windows compilation.
> Allows {type} and {istype} to work on any object.
